### ISSUE TITLE
hello_xr does not find active_runtime.json

### ISSUE THREAD

**Issue by Meakk** [KhronosGroup/OpenXR-SDK-Source#10]
I successfully compiled all the repository but had a runtime error when executing hello_xr example:

```
$ ./hello_xr -g OpenGL
[13:27:19.145][Info   ] Press any key to shutdown...
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::createIfValid failed to open /usr/local/share/openxr/0/active_runtime.json.  Does it exist?
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to find a valid runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
[13:27:19.155][Error  ] XrResult failure [-13]
    Origin: xrEnumerateInstanceExtensionProperties(layerName, 0, &instanceExtensionCount, nullptr)
    Source: ../src/tests/hello_xr/openxr_program.cpp:148
```

It looks that the file `/usr/local/share/openxr/0/active_runtime.json` is missing on my system.  
Is there some hardcoded path somewhere or maybe OpenXR is trying to create the file without access?

**Comment by daveh-lunarg** [comment]
You need to have an OpenXR runtime installed on your system before running hello_xr.  The `active_runtime.json` file is read by the loader to learn the location and properties of the installed runtime.

If you don't have one installed, there is a prototype runtime from Collabora linked on the main OpenXR landing page, here:  https://www.khronos.org/openxr.  If you have a runtime installed, but the json file isn't in the default path, you can direct the loader to it by setting an `XR_RUNTIME_JSON` environment variable to point to it.
