### ISSUE TITLE
Fix loader tests

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-SDK-Source#107]
It looks like there are some loader tests but they definitely aren't being run right now. This should be resolved.

**Comment by daveh-lunarg** [comment]
PR #119 fixes a bunch of loader_test issues, now runs 251 pass / 0 fail on Win10. 

Still needs work on the Linux paths.

**Comment by daveh-lunarg** [comment]
Still needs PR #123 and MR #1540 on Windows. And undoubtedly some Linux-specific updates. 

Closing this general issue, to be replaced with individual specific issues as found.
