### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by YTN0** [KhronosGroup/OpenXR-SDK-Source#113]
I am trying to figure out how to use the SDK in a C# project, however, it doesn't look like the pre-built DLLs support C# (i.e. they cannot be added as a reference to a C# project).

There also isn't any included .cs wrapper file that declares the DLLImports for the various functions.

Is this something that will be added at some point? Or am I missing some easy way to get this to work with my C# project?

Thanks!

**Comment by brycehutchings** [comment]
The OpenXR Loader DLL exports C symbols. C# can interop with the loader, but it requires using P/Invoke and marshaling. Referencing the a native DLL will not work from a managed project. Hopefully someone will make a managed interop library, but right now there isn't any public one that I know of.

**Comment by YTN0** [comment]
@brycehutchings  Thanks for the info!

**Comment by rpavlik** [comment]
If there's a tool that generates the dllimports for Vulkan, it may also work for OpenXR, since the XML format is closely related.

**Comment by lostmsu** [comment]
@rpavlik which tool are you referring to? Found the DLLs in [OpenXR.Loader NuGet packages](https://www.nuget.org/packages/OpenXR.Loader/). But they are for Windows only.

**Comment by rpavlik** [comment]
I am not aware of any tool, I'm just saying that if there is one, it might be compatible.

Yes, that NuGet package is for use with C/C++ "native" (Windows).

**Comment by Perksey** [comment]
Hi there! I'm the maintainer of [Silk.NET](https://github.com/Ultz/Silk.NET) - a bindings library to loads of APIs such as OpenGL, OpenAL, OpenCL, Assimp, Vulkan, GLFW, and soon OpenXR.

If all goes well we'll get experimental OpenXR bindings by the end of the night. However, take them with a grain of salt as this will be a preview package until at least the end of the year.

Just thought I'd let you know!

EDIT: I forgot code review exists, it’ll probably be next week now

**Comment by Perksey** [comment]
Good news! Silk.NET's OpenXR support for C# is live now as part of a preview:

https://nuget.org/packages/Silk.NET.OpenXR
https://github.com/Ultz/Silk.NET/tree/2.0/src/OpenXR

**Comment by rpavlik** [comment]
Closing as out of scope, there are community projects doing this: e.g., Silk.NET looks increasingly mature and is under the .NET foundation now: https://github.com/dotnet/Silk.NET and StereoKit https://stereokit.net/ is working on OpenXR support
