### ISSUE TITLE
Misleading use of `xrLocateViews` before `xrWaitFrame` in spec example

### ISSUE THREAD

**Issue by Sgeo** [KhronosGroup/OpenXR-SDK-Source#134]
In https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#example_view_configurations_code, the sample code shows an `XrTime displayTime` assumed to be previously initialized, then uses `xrLocateViews` before `xrWaitFrame`, even though if I understand correctly, `xrWaitFrame` should be used to initialize `displayTime`

**Comment by yl-msft** [comment]
Created internal issue #1227 to track this and find solution with working group.

**Comment by Sgeo** [comment]
I'm not sure if this should get its own ticket, but in the same sample code, there's an initialization `XrViewState viewState{};`, which is incorrect: It should be `XrViewState viewState{XR_TYPE_VIEW_STATE}`;

**Comment by rpavlik** [comment]
This is resolved in 1.0.4
