### ISSUE TITLE
Methods defined in openxr_platform.h  such as XrGraphicsRequirementsOpenGLESKHR have no impemention in openxr_loader.so

### ISSUE THREAD

**Issue by Lagrange1027** [KhronosGroup/OpenXR-SDK-Source#174]
Hi  rpavlik:
I find methods defined in openxr_platform.h  such as XrGraphicsRequirementsOpenGLESKHR have no implementationin openxr_loader.so. when i call these method,i encount a Compile  error msg: undefined reference to 'xrGetOpenGLESGraphicsRequirementsKHR'.
should i implement these methods in loader_core.cpp or  somewhere.
 thanks very much

**Comment by brycehutchings** [comment]
Extension functions are only available for lookup through xrGetInstanceProcAddr at runtime.

**Comment by Lagrange1027** [comment]
> Extension functions are only available for lookup through xrGetInstanceProcAddr at runtime.
I get that ,thanks very much

**Comment by rpavlik** [comment]
So this is by design, that extension functions are not exported from the loader. However, it is confusing since the prototypes are available by default from the header - we'll address this part of it shortly.
