### ISSUE TITLE
Build broken with latest Vulkan headers

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-SDK-Source#180]
cc @oddhack 

Looks like `VK_DEBUG_REPORT_OBJECT_TYPE_OBJECT_TABLE_NVX_EXT` got removed, and while OpenXR didn't use it directly, it was mentioned in an enum list:

```
_(OBJECT_TABLE_NVX)
```

Not sure if this counts as Vulkan breakage, but I suspect the right solution for now is for us to just remove all X-suffixed entries from those enum lists. (Ideally Vulkan would have something like our openxr_reflection.h header so no app-made list like this would be required.)

See also:

- Bug report in Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958837
- Patch in ArchLinux: https://aur.archlinux.org/cgit/aur.git/tree/0001-hello_xr-vulkan-Fix-build-with-Vulkan-headers-1.2.13.patch?h=openxr-loader-git

**Comment by oddhack** [comment]
NVX is an NVIDIA "experimental" extension and as such, is subject to whatever changes they decide to make at any time (including completely withdrawing the extension). Similarly for Khronos "provisional" extensions, which status currently includes the entire ray tracing stack of three extensions, although the provisional extensions at least have to be explicitly opted-in via a separate header file. We have struggled with how to expose bleeding-edge functionality and this is the best answer we currently have.

While it may not be straightforward for this project, using vk.xml to find out what interfaces  are actually supported might be somewhat more future-proof. That won't tell you a lot about how underlying functionality of an experimental / provisional extension may have changed, but at least you could avoid compilation errors.

**Comment by oddhack** [comment]
N.b. I'm not familiar with the reflection header - is that a string-to-API name mapping? If you're using a generator script for it, we could likely incorporate that without much trouble. The 'vkapi.py'  generation target in Vulkan-Docs could probably be used in similar fashion.

**Comment by rpavlik** [comment]
Yeah it's a generation script (actually, mostly in a jinja2 template for ease of maintenance)  It creates a bunch of macros that let you do things like make a type/enum to string mapping, etc. I'll look into porting it to vulkan when I get a chance, if nobody beats me to it.

Ok, I'll submit a patch for the Debian package
