### ISSUE TITLE
Build fails on Visual Studio 2019 16.6 Preview

### ISSUE THREAD

**Issue by matthieucoquet** [KhronosGroup/OpenXR-SDK-Source#184]
I'm using [Visual Studio 16.6 Preview](https://visualstudio.microsoft.com/vs/preview/). The final behaviour might change but I thought I should raise an issue anyway.

There is a warning in `openxr_program.cpp`:
```
src\tests\hello_xr\openxr_program.cpp(348,31): error C2220: the following warning is treated as an error
src\tests\hello_xr\openxr_program.cpp(348,31): warning C5208: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes
src\tests\hello_xr\openxr_program.cpp(348,31): message : to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
```
Here is a copy of the code:
```
using InputState = struct {
    XrActionSet actionSet{XR_NULL_HANDLE};
    XrAction grabAction{XR_NULL_HANDLE};
    XrAction poseAction{XR_NULL_HANDLE};
    XrAction vibrateAction{XR_NULL_HANDLE};
    XrAction quitAction{XR_NULL_HANDLE};
    std::array<XrPath, Side::COUNT> handSubactionPath;
    std::array<XrSpace, Side::COUNT> handSpace;
    std::array<float, Side::COUNT> handScale = {{1.0f, 1.0f}};
    std::array<XrBool32, Side::COUNT> handActive;
};
```
The error is still there using `/permissive-`

From a quick look online, it looks like [C++20 is getting more restrictive for unnamed class](http://eel.is/c%2B%2Bdraft/dcl.typedef#10.2). I'm compiling using the default `std:c++14`.

I'm not sure why an unnamed class is used. However, it compiles when using:
 ```
struct InputState {
    ...
};
```

I know this is not an issue for the currently supported compilers. Should I submit a pull request anyway?

**Comment by rpavlik** [comment]
I don't really know why an unnamed class was used either. That inputState struct has been quite the source of (unnecessary) portability bugs, so happy to see it improved :)
