### ISSUE TITLE
Space missing in xr.xml for struct XrSpatialAnchorCreateInfoMSFT

### ISSUE THREAD

**Issue by matthieucoquet** [KhronosGroup/OpenXR-SDK-Source#187]
In `xr.xml`, for struct `XrSpatialAnchorCreateInfoMSFT`, I think this line is missing a space between `</type>` and `<name>`:
```
<member values="XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT"><type>XrStructureType</type><name>type</name></member>
```
I think it should be:
```
<member values="XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT"><type>XrStructureType</type> <name>type</name></member>
```
Currently, there is no issue with the files generated. But I tried to change the generator of `openxr.hpp` and realised the cdecl of member type is wrong for this struct. The output was `StructureTypetype` instead of `StructureType type`

**Comment by rpavlik** [comment]
Ooh, good catch. Interesting that none of the fancy CI caught this.

**Comment by rpavlik** [comment]
OK, I've made a fix for this internally, it will be in the next release. Thanks for reporting this!
