### ISSUE TITLE
Render to texture workflow

### ISSUE THREAD

**Issue by pkovacs86** [KhronosGroup/OpenXR-SDK-Source#189]
My renderer producing two ID3D11Texture2D* textures with the rendered scene.
Is it possible to use them as XrSwapchainImageBaseHeader* when calling xrEnumerateSwapchainImages function?

Thank you,
Peter

**Comment by pkovacs86** [comment]
Okay, seems it is solved.
Anyone can use the OpenXR Plugin in ApertusVR
video:
https://nextcloud.sztaki.hu/s/EKj8tbfLJ7yaD6A
screenshot:
https://postlmg.cc/kVBL4jr2
source code:
https://github.com/MTASZTAKI/ApertusVR/tree/0.9.1

**Comment by rpavlik** [comment]
Looks nice!

I took a quick look at your code (well, the latest commit) - the enumerate swapchain images usage looks correct. However, it does look like you're rendering to a different texture and copying, which is less than optimal performance-wise. If possible, you want to render directly into the texture created by the runtime.

You might want to try https://community.khronos.org/ for future questions of this type.
