### ISSUE TITLE
OpenXR include directory included as PRIVATE, should be PUBLIC

### ISSUE THREAD

**Issue by madsbuvi** [KhronosGroup/OpenXR-SDK-Source#195]
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/51cade1763267c750f53cefa9834644c7e7b37f3/src/loader/CMakeLists.txt#L91

If the openxr include directory were included as PUBLIC rather than PRIVATE for the openxr_loader target, it would simplify the process of importing that target using modern cmake's FetchContent. PUBLIC includes of a target are automatically included for any targets linking against that target.
Currently I have to manually include the directory instead.

Ref [this thread](https://gitlab.com/OpenMW/openmw/-/merge_requests/251#note_383337564) where we encountered the issue.

**Comment by rpavlik** [comment]
So I definitely thought we had fixed this, but I guess not. It has been worked around in the config module, not sure if that's suitable for FetchContent, but it's still there in general.

**Comment by rpavlik** [comment]
Oh, we fixed it for install interface but not build interface:  https://github.com/KhronosGroup/OpenXR-SDK-Source/commit/6abd9ccc8641c9b7190687ef68e7d42e1615f5ce
