### ISSUE TITLE
Build fails under MSVC 2017

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-SDK-Source#197]
> OpenXR-SDK\src\common\filesystem_utils.cpp(219): error C3861: 'PathCanonicalizeW': identifier not found

Looks like this is supposed to come from Shlwapi.h ([docs](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathcanonicalizew)) which isn't included anywhere that I can see.

**Comment by brycehutchings** [comment]
Looks like this was introduced in 1.0.10 because this code only compiles for Windows when C++17 std::filesystem isn't available and we don't build that way in our CI pipeline. Preferably we can solve this without adding a dependency on Shlwapi since it is not available on the UWP platform.

**Comment by brycehutchings** [comment]
I believe we can use PathCchCanonicalize instead.

**Comment by rpavlik** [comment]
I suspect that for @Ralith's purposes, just adding the define to use std::filesystem to the build system would be sufficient, but it does sound like we should probably add (yet) another case to CI.
