### ISSUE TITLE
Failed to find XR_API_LAYER_PATH via XrApiLayer_core_validation.json

### ISSUE THREAD

**Issue by Phildo** [KhronosGroup/OpenXR-SDK-Source#203]
I built this repository on Windows, and pointed my XR_API_LAYER_PATH to its corresponding build/src/api_layers directory.

After doing this, my openXR application correctly found the API layer, but was unable to open it with ERROR_FILE_ACCESS_ERROR.

The XrApiLayer_core_validation.json file looked like the following:

```
{
    "file_format_version": "1.0.0",
    "api_layer": {
        "name": "XR_APILAYER_LUNARG_core_validation",
        "library_path": "XrApiLayer_core_validation.dll",
        "api_version": "1.0",
        "implementation_version": "1",
        "description": "API Layer to perform validation of api calls and parameters as they occur"
    }
}
```

but when I changed the library_path to an absolute path, it was fixed.

I was briefly told by Ryan Pavlik on a slack message that what needs fixing is that "library_path" needs a .\\ in front, to search relative to the manifest.

**Comment by rpavlik** [comment]
Yeah I think we had an action item to add `./` to all those generated manifests on Windows, but it got lost somewhere along the way.

**Comment by rpavlik** [comment]
Looks like they are there now, not sure when they got added but this is fixed.
