### ISSUE TITLE
Loader not GPL 2 compliant?

### ISSUE THREAD

**Issue by mrwonko** [KhronosGroup/OpenXR-SDK-Source#205]
I want to use OpenXR in GPL 2 code, but think this is impossible.

It is my understanding that to use OpenXR I need both the headers and the loader library. The header files [recently got dual-licensed with MIT](https://github.com/KhronosGroup/OpenXR-Docs/issues/3) so that they are GPL-compliant, but it is my understanding that I also need the loader library to do anything with them, and it is my understanding that this library in turn is exclusively Apache 2 licensed, which in turn apparently makes it incompatible with GPL 2.

Please correct me if I got any of that wrong, or if I got it right, please provide a way to use OpenXR in GPL 2 projects.

**Comment by rpavlik** [comment]
Hm, this is a good question. I wonder how Vulkan did this. Does dynamically/late loading the loader DLL/SO solve your issue? If not, we may need to relicense the loader parts too.

cc @oddhack

**Comment by mrwonko** [comment]
I don't think dynamic/late loading gets around the GPL, I believe only communication via pipes/sockets is legal.

**Comment by jbkempf** [comment]
Dlopening does not solve the issue.

**Comment by rpavlik** [comment]
So dual-licensing the rest of the loader code would work, then?

(How does Vulkan get around this? Is it because it's installed system-wide, so it's a "system library"?)

**Comment by oddhack** [comment]
> (How does Vulkan get around this? Is it because it's installed system-wide, so it's a "system library"?)

AFAIK this issue hasn't come up yet for https://github.com/KhronosGroup/Vulkan-Loader, though I don't keep a close eye on that. Probably worth asking Karen Ghavam at LunarG if they've run into this concern.

**Comment by KarenGhavam-lunarG** [comment]
We have not had any concerns about the Apache2.0 license for the loader come into the Loader repository.
I am not an expert on licenses to know if it really is an issue to have the Loader licensed as Apache 2.0 for applications using GPL 2. 
If there was a desire to change the loader license, it would also need to be run through Khronos for agreement on the license change. The current selection of the Apache 2.0 license was based on Khronos guidance of which license to use at the time when Vulkan first went public.

**Comment by rpavlik** [comment]
We do have a process for moving things to the dual-license upon request, which I imagine I'll propose.

**Comment by jbkempf** [comment]
> I am not an expert on licenses to know if it really is an issue to have the Loader licensed as Apache 2.0 for applications using GPL 2.

It is an issue.

**Comment by rpavlik** [comment]
OK, so I have gone through, and I think the following lists all the files that go into the loader that are Apache-2.0 only right now:

- `src/common/filesystem_utils.cpp`
- `src/common/filesystem_utils.hpp`
- `src/common/hex_and_handles.h`
- `src/common/loader_interfaces.h`
- `src/common/object_info.cpp`
- `src/common/object_info.h`
- `src/common/platform_utils.hpp`
- `src/common/xr_dependencies.h`
- `src/loader/api_layer_interface.cpp`
- `src/loader/api_layer_interface.hpp`
- `src/loader/exception_handling.hpp`
- `src/loader/loader.rc`
- `src/loader/loader_core.cpp`
- `src/loader/loader_instance.cpp`
- `src/loader/loader_instance.hpp`
- `src/loader/loader_logger.cpp`
- `src/loader/loader_logger.hpp`
- `src/loader/loader_logger_recorders.cpp`
- `src/loader/loader_logger_recorders.hpp`
- `src/loader/loader_platform.hpp`
- `src/loader/manifest_file.cpp`
- `src/loader/manifest_file.hpp`
- `src/loader/openxr-loader.def`
- `src/loader/openxr-loader.map`
- `src/loader/runtime_interface.cpp`
- `src/loader/runtime_interface.hpp`

plus some generated files: 

- `xr_generated_dispatch_table.c`
- `xr_generated_dispatch_table.h`
- `xr_generated_loader.cpp`
- `xr_generated_loader.hpp`
- `common_config.h`

If those get relicensed to "Apache-2.0 OR MIT", would that be sufficient? (There's a bit of a process required still, but I want to wait to make sure I have everything in one shot. I think that should cover it, though: the only other thing in the build is the C++ standard library and system headers, and the jsoncpp library which is MIT already.)

**EDIT**: I had missed `src/common/extra_algorithms.h` - consider that also on the list.

**Comment by jbkempf** [comment]
@rpavlik "Apache2.0 or MIT" or "Apache2.0 or MIT+Patents clause" is usually enough to be LGPLv2.1+ _(and therefore GPLv2)_ compatible. So, yes.

**Comment by rpavlik** [comment]
I was more-so asking about the list of files: if I can get approval, the license will be the SPDX expression "Apache-2.0 OR MIT" - that's the only option available through the internal process, so let's not muddy the waters or say the p-word. Glad we agree that MIT is GPL2 compatible though :D

**Comment by jbkempf** [comment]
:pray:

**Comment by rpavlik** [comment]
I'll take that as a "the list of files looks right to me" :)  (I did go so far as to use Doxygen to make an include graph, so I'm pretty sure I got them all.)

**Comment by rpavlik** [comment]
OK, 1.0.14 should have resolved this now!
