### ISSUE TITLE
Unable to build SDK

### ISSUE THREAD

**Issue by chinmay-bhat** [KhronosGroup/OpenXR-SDK-Source#21]
Hi, I'm following the BUILDING.md file and am unable to build the SDK.
(Windows 64-bit, VS 2017)

cmake -G "Visual Studio 15 Win64" ..\..

-- Could NOT find VulkanHeaders (missing: VulkanHeaders_INCLUDE_DIR)
-- Could NOT find VulkanRegistry (missing: VulkanRegistry_DIR)
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
-- Could NOT find glslc, using precompiled .spv files
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

**Comment by rpavlik** [comment]
I believe it should be buildable now without Vulkan, if you update your source. Re-open if you still have trouble.
