### ISSUE TITLE
Loader uses pathcch.lib which is only available on Windows 8 and later

### ISSUE THREAD

**Issue by brycehutchings** [KhronosGroup/OpenXR-SDK-Source#214]
This is an unintentional side-effect of #198. The loader should use something else that is available on Windows 7 too. Since symbolic links are not an important use case for the loader on Windows, perhaps std::filesystem::absolute can be used instead?

**Comment by rpavlik** [comment]
does the issue associated with https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/198 (that is, broken on UWP) apply to it too? Or do we just null this out and make it more of a no-op? I swear we had a discussion about this in the past week, must have been on mattermost or something.

**Comment by brycehutchings** [comment]
Yeah, we talked about it on Mattermost. The conclusion was that we can make the canonical functions no-op on WIN32 builds since the symlink-following functionality isn't needed on Windows. I can make this fix now that we have a solution that has some agreement.
