### ISSUE TITLE
HandTracking Extension: Bone Names

### ISSUE THREAD

**Issue by 1runeberg** [KhronosGroup/OpenXR-SDK-Source#223]
We're (Valve) working on migrating our sample SteamVRInput skeleton to OpenXR. 

It'd probably be useful to have bone names also specified in the spec rather than just the hierarchy or enums, so skeletons made for OpenXR can be easily interchangeable across applications / engines.

Case in point is in Unreal's LiveLink system, using this along with correct heirarchy ensure that our skeleton works seamlessly with UE4's upcoming OpenXR Handtracking plugin in UE 4.26:

![image](https://user-images.githubusercontent.com/17371351/99318034-14ecf100-28bb-11eb-8ada-30367d552453.png)

**Comment by 1runeberg** [comment]
Thanks Ryan! Will check it in the internal one then. Cheers.

**Comment by rpavlik** [comment]
Resolved in 1.0.15
