### ISSUE TITLE
.

### ISSUE THREAD

**Issue by BattleAxeVR** [KhronosGroup/OpenXR-SDK-Source#226]

**Comment by rpavlik** [comment]
Can you use the "OpenXR Developer Tools for Windows Mixed Reality" app from the Microsoft Store to tell us which runtime you're actually using? (I was pretty sure SteamVR's runtime didn't handle devices that do their own rendering) It will be on the "System Status" page, like this: 

![image](https://user-images.githubusercontent.com/61129/101395645-d92cc200-388f-11eb-9915-d3da34bf576a.png)

**Comment by BattleAxeVR** [comment]
Sorry for the delay Ryan.

I installed the dev tool and it gave me exactly the same thing, showing SteamVR's openxr runtime is indeed the one I'm using. I've been using reg files to toggle between Oculus and SteamVR runtimes. SteamVR also has a button that sets itself as the default runtime, which achieves the same thing.

![image](https://user-images.githubusercontent.com/11604039/101717434-3f227080-3a6d-11eb-8c2b-ccedfa9eb0db.png)

**Comment by BattleAxeVR** [comment]
To answer your question, yes indeed it is possible to do this: OpenXR app -> SteamVR's OpenXR runtime -> Virtual Desktop's compositor. The main issue here for me is figuring out where the problem lies, it could be SteamVR or VirtualDesktop or the OpenXR hello_xr app. I just don't know because none of those things are open source. At least if you can repro the bug and maybe even confirm there's indeed nothing wrong with the sample code, we can forward the bug to SteamVR team. It is probably a bug there but I wanted to try here first, for obvious reasons (Steam people might balk at assuming a bug is in their compositor without proper vetting that it is, rather than a bug in the calling software).

**Comment by rpavlik** [comment]
well, OpenXR hello_xr app is open source, of course. If I had to guess, it's probably a bug in SteamVR's OpenXR impl, or an incompatibility between that and Virtual Desktop. Is your setup common, faking a runtime to SteamVR to remote-drive a quest? It sounds like the kind of thing where "if it breaks, you get to keep both pieces". I can ping a steamvr person, but my suspicion is they'll say "it's not meant to do that"

**Comment by BattleAxeVR** [comment]
Update: this bug has definitely nothing to do with Virtual Desktop, I just double checked with the latest OpenXR SDK source and SteamVR client (both beta and mainline) when using Oculus Link. So, standard Oculus runtime being called via SteamVR's OpenXR runtime.

The issue is actually worse now, because it won't initialize even the first time until I manually reset the view. So there's a 100% repro case here.

Do you have an Oculus headset you could test your hello_xr app with? I guarantee you'll see the problem right away. I am reluctant to say whether it's a bug in hello_xr or SteamVR, because SteamVR was working right, at least the first run, before. There hasn't been an update to SteamVR for a couple weeks, the only thing that's changed is this repo and the problem is worse now. It leads me to think the bug is here somewhere.

**Comment by BattleAxeVR** [comment]
[RegToggleOpenXRRuntime.zip](https://github.com/KhronosGroup/OpenXR-SDK-Source/files/5675127/RegToggleOpenXRRuntime.zip)

These .reg files are handy to switch between Oculus native OpenXR runtime and SteamVR's to compare.

**Comment by BattleAxeVR** [comment]
When I get the chance I'll test it with my Rift CV1 just to see. Pretty sure it'll be the same thing. 

Thanks for taking the time here, by the way. I really need this OpenXR integration into my engine to be 100% reliable for dev. I need to test my game wirelessly too, via Virtual Desktop but you should be able to repro this bug using Oculus Link.

**Comment by rpavlik** [comment]
I do not have any Oculus hardware besides a pile of GearVRs. I'm not sure if using the SteamVR OpenXR runtime on top of their Oculus desktop driver is supported, but I've reached out to a SteamVR contact for help.

I can do you one better than the reg files: someone shared this script with me the other day https://github.com/maluoi/StereoKit/blob/master/Set-OXR-Runtime.ps1

It seems very strange that a change in this repo would cause this behavior, especially since senior devs from both Oculus and Valve work on this same hello_xr - I'm just the spec editor and thus I've taken the role of public maintainer as well. I don't think anything relevant changed in 1.0.13. The start of loader and hello_xr changes in 1.0.13 are here: https://github.com/KhronosGroup/OpenXR-SDK-Source/commit/eedc7df3d99ca7a468d63a574629a9935716ae0b#diff-f08ca761c0763c9c065d6c4955ec71a33e921193a0e75e93ffbac38baa8d1826

**Comment by BattleAxeVR** [comment]
Ryan you totally should buy a Quest 2 mate :) Even if you're anti-FB, it's the best deal there is right now and probably worth it just to test for compatibility alone. Plus it's the highest res HMD that works wirelessly in the world right now (the G2 is better obviously but it's wired only, which to me is more like a side-grade than an upgrade. Wireless VR from your PC is too good, even with the occasional headache or increased latency).

**Comment by BattleAxeVR** [comment]
The bug is still there with latest SteamVR and Oculus runtimes. I've started the process of escalating this so people who can see how serious it is that neither runtime works properly in the basic hello_xr app.

This is basic functionality (tracking initialization and state, as well as framerate) that's broken, nothing else matters until these two issues are fixed IMO. Or at least one of them so I can iterate productively until the other is fixed.

![image](https://user-images.githubusercontent.com/11604039/106394223-82dc8b00-63c9-11eb-8c24-ff1428bd6040.png)

**Comment by rpavlik** [comment]
There must be something strange about your configuration, because the conformance tests are much stricter than just running hello xr, and they set up and tear down sessions and instances repeatedly. I'd definitely ask your runtime vendor, and make sure you're using a conformant runtime (SteamVR is not one yet, and I'm pretty sure it won't be conformant when used with Oculus drivers - but the Oculus runtime itself is conformant.)

**Comment by BattleAxeVR** [comment]
It's certainly possible there's an issue on my PC, but when you have n > 1 people who have the same issue, then it can't simply be my machine, logically, now can it. It would be nice if you could actually try to reproduce this issue yourself but as you said, you don't own any Oculus HMDs. Not sure the point in discussing this.

**Comment by BattleAxeVR** [comment]
Both of my bug reports are listed as "waiting for reporter". What does that mean, exactly? Is anyone taking a look at these?

Your comment about Oculus runtime being "conformant" is weird, tbh. It also logically cannot be "something strange about my configuration" when the Oculus runtime issue has been independently corroborated by another dev. 

This appears to be a huge waste of time. These are serious bugs that I opened months ago Ryan. Is anyone looking into them or not?

**Comment by rpavlik** [comment]
Well, this is not the right place for them. I do the editing and maintenance of the specification and SDK. I have tried to offer my best effort in helping you diagnose the issues, in case they're related to code in this repo, but fundamentally you're reporting runtime issues to me, which I have no control over or insight into. Please contact the runtime vendors through their developer relations contacts.

**Comment by bradgrantham-lunarg** [comment]
Hi, @BattleAxeVR !  To add to what @rpavlik said, the OpenXR SDK is a Khronos-provided piece of software that allows applications to load and use any vendor's conformant OpenXR runtime.

This repository only contains the specification, headers, and sources that are not specific to any runtime.  @rpavlik doesn't work for Facebook (i.e. producers of the Oculus Rift series).

Issues posted _here_ that are specific to a _runtime_ (like Facebook's runtime for Quest, or WinMR on the Samsung Odyssey, or SteamVR) may not get any responses from the companies which produce the products that use that runtime.  I think you'll have a lot more luck with performance problems you're seeing on Quest if you submit issues to Facebook developer relations.

Good luck!

**Comment by BattleAxeVR** [comment]
I repro'ed this particular bug with the SteamVR runtime in Unreal (which hangs). 

The other issue exists in hello_xr but not Unreal, using the Oculus runtime. Therefore the bug is here. I'm closing this one but I'll keep the other open until I have a solution.
