### ISSUE TITLE
Release signing key has expired

### ISSUE THREAD

**Issue by svenstaro** [KhronosGroup/OpenXR-SDK-Source#238]
Hey, thanks for being an upstream that signs their releases. Sadly, your signing key is outdated. Could you create a new cross-signed key that's valid? It's currently not a deal-breaker as long as you don't revoke the old key but please take care of it. :)

```
gpg --verify OpenXR-SDK-Source-release-1.0.14.tar.gz.asc
gpg: assuming signed data in 'OpenXR-SDK-Source-release-1.0.14.tar.gz'
gpg: Signature made Thu 28 Jan 2021 10:06:29 PM CET
gpg:                using RSA key C35A8C8763398375BBFF3FDB1629319BCA0E17AE
gpg:                issuer "rpavlik@collabora.com"
gpg: Good signature from "Ryan Andrew Pavlik <ryan.pavlik@collabora.com>" [expired]
gpg:                 aka "Ryan Andrew Pavlik <rpavlik@collabora.com>" [expired]
gpg:                 aka "Ryan Andrew Pavlik <rpavlik@collabora.co.uk>" [expired]
gpg:                 aka "Ryan Andrew Pavlik <ryan.pavlik@collabora.co.uk>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: F029 455E AB70 F520 FF4A  03BD 7F53 4CD5 6F00 321E
     Subkey fingerprint: C35A 8C87 6339 8375 BBFF  3FDB 1629 319B CA0E 17AE
```

**Comment by rpavlik** [comment]
Thanks for your appreciation - trying to do this the "official" and "best" way :) I'm even signing the release tags, and the keys are on a hardware token, etc. Updating these (with the private keys kept offline, etc) was a fairly large portion of the time spent on this release 🤣 

So I did update the expiration and push it to the various keyservers. I think that's the thing I'm supposed to do? (Still getting the hang of best practices for GPG usage - so please let me know if I goofed up somehow.) My keys (without third party sigs, I think) are canonically on https://keys.openpgp.org/ but also pushed (with signatures) to the Ubuntu and sks-pool key servers. https://keys.openpgp.org/search?q=C35A8C8763398375BBFF3FDB1629319BCA0E17AE

![image](https://user-images.githubusercontent.com/61129/106496397-75cfa280-6482-11eb-872d-bdae36ca7598.png)

![image](https://user-images.githubusercontent.com/61129/106496608-b2030300-6482-11eb-820f-684346f692a0.png)

I did recently notice there's an option for including public keys in the signatures, not sure if that would be a useful thing to do as well. It wouldn't help, e.g. Debian, where I include my public key in the packaging files for verification, but it might help the common consumers that use gpg.

**Comment by svenstaro** [comment]
Yep, seems good now! Now we just need a new signed release. :)

**Comment by rpavlik** [comment]
So I extended those keys before I signed the releases - is there some reason I need to re-sign them? I checked locally at least and I got

```
gpg --verify OpenXR-SDK-Source-release-1.0.14.tar.gz.asc
gpg: assuming signed data in 'OpenXR-SDK-Source-release-1.0.14.tar.gz'
gpg: Signature made 1/28/2021 3:06:29 PM Central Standard Time
gpg:                using RSA key C35A8C8763398375BBFF3FDB1629319BCA0E17AE
gpg:                issuer "rpavlik@collabora.com"
gpg: Good signature from "Ryan Andrew Pavlik <ryan.pavlik@collabora.com>" [ultimate]
gpg:                 aka "Ryan Andrew Pavlik <rpavlik@collabora.co.uk>" [ultimate]
gpg:                 aka "Ryan Andrew Pavlik <rpavlik@collabora.com>" [ultimate]
gpg:                 aka "Ryan Andrew Pavlik <ryan.pavlik@collabora.co.uk>" [ultimate]
```

**Comment by svenstaro** [comment]
Nope, we're good!
