### ISSUE TITLE
Update jsoncpp to 1.9.4 for security fixes

### ISSUE THREAD

**Issue by patrto** [KhronosGroup/OpenXR-SDK-Source#265]
1.9.4 has OSS-Fuzz security fixes as well as other security enhancements:

https://github.com/open-source-parsers/jsoncpp/releases/tag/1.9.4

**Comment by rpavlik** [comment]
I have made an internal merge request doing this update, and assuming it doesn't break anything, it will be in the next release. Thanks for reporting this!

**Comment by rpavlik** [comment]
This was in a release some time ago, sorry I somehow missed closing this. Thanks!
