### ISSUE TITLE
Linux active runtime search

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-SDK-Source#28]
The draft loader design document (#27) states:

> On Linux, the active runtime information is contained inside a JSON-formatted file located under the folder:
>
>     /usr/local/share/openxr/<major_api_version>`

I propose a different strategy: select the first `openxr/$VERSION/active_runtime.json` found by searching first `$XDG_CONFIG_HOME`, then the elements of `$XDG_CONFIG_DIRS`, in order. If an environment variable is not set or the process is SUID, the freedesktop.org fallback values are used, unless a more appropriate fallback is specified by the target environment.

This has a number of advantages:

- Flexibility: a user who wishes to configure a default runtime other than the one configured globally can do so by placing a file in `$XDG_CONFIG_HOME/openxr/$VERSION/active_runtime.json` without requiring elevated privileges.
- Convention: `/usr/local` is not a standard prefix for packages installed through the system's package manager, and runtime packages targeting that location are unlikely to be supported by major distributions. It is also not a standard prefix for administrator-controlled configuration files associated with system infrastructure such as a package-manager-installed OpenXR runtime or loader.
- Portability: Not all distributions implement the filesystem hierarchy standard. For example, `/usr/local` does not exist on NixOS, and indeed no NixOS packages may write to `/usr` at all. Such environments provide XDG environment variables identifying the correct locations, allowing precompiled binaries to Just Work even if they were not specifically targeted to the environment. Such environments can also override the fallback paths in their packaging of the OpenXR loader.

**Comment by daveh-lunarg** [comment]
Currently we have just a two-level search for the json file: First use whatever is defined by environment variable `XR_RUNTIME_JSON`, or second if that envar doesn't exist then look in a single well-defined path (or Windows registry key). If that well-defined path on Linux were defined to be `$XDG_CONFIG_HOME/openxr/$VERSION/active_runtime.json`, would that be sufficient? I'm a little leery of searching a hierarchy of paths because I see it as potential way to load an unintended runtime.

@rpavlik @insko, I don't know who's most suited to weigh in on the subtleties of Linux path searches, other than it's probably not me. e.g. is there any situation where $XDG_CONFIG_HOME might not be defined, and if so is there an appropriate one-path-fits-all fallback location?

**Comment by Ralith** [comment]
> If that well-defined path on Linux were defined to be `$XDG_CONFIG_HOME/openxr/$VERSION/active_runtime.json`, would that be sufficient?

That would be an improvement in some regards, but it sacrifices the capability to have a system-wide default runtime. In particular, it's unusual for system package management tools to write to `$HOME` (which `$XDG_CONFIG_HOME` usually lies beneath), so a user who installs a runtime would not have a working configuration out of the box, and would need to (use some tool to) configure their personal active_runtime.json by hand.

> I'm a little leery of searching a hierarchy of paths because I see it as potential way to load an unintended runtime.

It's very typical for Linux software to find configuration by searching user-specific paths, followed by system paths, because "global defaults that can be customized without privileges" is a useful pattern. I think the risk here is much less than the benefit, particularly considering how conventional and hence unsurprising this pattern is.

> is there any situation where $XDG_CONFIG_HOME might not be defined, and if so is there an appropriate one-path-fits-all fallback location?

[The basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) specifies sane defaults when the environment variables are not defined. In fact, it is common for the variables to be left undefined, as these defaults are usually the desired behavior.

**Comment by Ralith** [comment]
Anything I can do to move this forwards? I'd really like to get this resolved before people start distributing software with the loader built-in, setting the bad behavior in stone.

**Comment by rpavlik** [comment]
The proposed behavior seems reasonable enough. I'm assuming we want to permit users to specify their own runtime preference, since we're giving them that ability through environment variables anyway.

**Comment by Ralith** [comment]
Correction to the proposal: the fallback value for `$XDG_CONFIG_HOME` should not be searched if the process is SUID/SGID, because user-controlled code should not be executed when running with some other user's privileges. The fallback value of `$XDG_CONFIG_DIRS` can still be searched because it refers to locations controlled by the system administrator.

I'm happy to write a PR for this behavior as soon as it's clear that it would be accepted.

**Comment by ChristophHaag** [comment]
You may have seen how Vulkan does it: https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md#icd-discovery-on-linux

Vulkan has this reasonable restriction too:

> $HOME is the current home directory of the application's user id; this path will be ignored for suid programs

There doesn't seem to be a clear consensus whether it would be accepted but personally I would like to see it work along these lines, so I would appreciate a PR even if it's not immediately accepted.

**Comment by Ralith** [comment]
> You may have seen how Vulkan does it

I actually [wrote](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1426) parts of that code, for the same motivations outlined here. The documentation you cite is a bit simplified. I maintain packages on a non-FHS distribution (NixOS) so I tend to run into these issues sooner than most.

> I would appreciate a PR even if it's not immediately accepted.

Alright, I'll see if I can draft something over the weekend.

**Comment by Ralith** [comment]
Drafted the changes in #51.
