### ISSUE TITLE
Is there any document for how to write openxr runtime from scratch?

### ISSUE THREAD

**Issue by wanhex** [KhronosGroup/OpenXR-SDK-Source#287]
we want to implement openxr runtime in out custom hardware which run our OS based on Androids.

Can we know how much work this job requires？

**Comment by wanhex** [comment]
can we know how many developers(such as software/framework/driver engineer)?

**Comment by rpavlik** [comment]
I'm not sure that anyone will describe their internal efforts to implement, and many are building on an existing internal API. There is no demo code or reference/sample implementation.

However, my team at Collabora has built, with the community, the Monado open-source runtime which does run on Android, which could be useful to you for adaptation and building your own runtime. https://monado.dev/ Collabora does provide consulting services on adapting it for customers' specific use cases. It has passed OpenXR conformance on its own in simulator mode, as well as when part of other vendors' runtimes: https://www.khronos.org/conformance/adopters/conformant-products/openxr  Feel free to email me so we can discuss further - my email is my github username at collabora.com

**Comment by rpavlik** [comment]
Closing as out of scope for the WG to estimate effort to build a runtime. The WG is putting efforts into improving Monado, so probably starting there is as close as we'll get to a recommendation.
