### ISSUE TITLE
xrCreateSession returns XR_ERROR_VALIDATION_FAILURE, but validation layer gives no information

### ISSUE THREAD

**Issue by waitingtocompile** [KhronosGroup/OpenXR-SDK-Source#288]
```C
    XrGraphicsBindingOpenGLWin32KHR binding = { XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR, NULL, wglGetCurrentDC(), wglGetCurrentContext() };
    XrSessionCreateInfo sessionCreateInfo = { XR_TYPE_SESSION_CREATE_INFO, &binding, 0, systemId};
    XrSession xrSession;
    XrResult result = xrCreateSession(context.xrInstance, &sessionCreateInfo, &xrSession);
```

Is returning XR_ERROR_VALIDATION_FAILURE. However, in spite of the validation layer being enabled and seemingly working correctly if I introduce errors into other openXR functions, no information is output by the layer on what exactly is being done wrong.

**Comment by waitingtocompile** [comment]
After extensive tinkering I've finally found the solution: I wasn't properly calling `xrGetOpenGLGraphicsRequirementsKHR` before session creation. However, the lack of information from the validation layer remains an issue, as well as the fact that no mention of this requriement exists in the specification for the graphics binding or session creation; the requirement is only listed in the specification for the offending function itself.

**Comment by rpavlik** [comment]
What runtime was this? We added an error code specifically for that (XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING) quite a while ago to help fix this problem.

The docs here do mention that error in the part that would get extracted to the ref pages. (between the parameters and the implicit valid usage, second paragraph) but that part doesn't explicitly list the functions, just the function name pattern. I see that the application must: part (with the list of explicit function names) does appear above the function, where it won't be seen in the ref page, was this the problem you hit? https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#session-creation (See second sentence of second paragraph).

**Comment by rpavlik** [comment]
I filed an issue to add such a check to the validation layer, since this seems like it's still tripping people up apparently.

**Comment by waitingtocompile** [comment]
I was experiencing the issue on SteamVR for windows.
