### ISSUE TITLE
Right eye with perspective distortion with multiview enabled in Vulkan on Oculus PCVR

### ISSUE THREAD

**Issue by Izhido** [KhronosGroup/OpenXR-SDK-Source#292]
Whoa. That was a hard title to write.

Here is the thing. An app I'm currently writing uses a shared codebase, based on OpenXR, to perform rendering in both standalone and PCVR modes in Oculus devices (Rift, Quest).

The standalone version performs quite nicely, and shows no undesired distortions whatsoever. That same code, when running in a desktop application for Windows (PCVR mode), is able to render fine in the left eye screen. The right eye, however, shows a noticeable perspective distortion, as in, objects are stretched and curved to the sides of the screen, with no plausible explanation.

Both standalone and PCVR apps use Vulkan, and both have the VK_KHR_multiview extension enabled. Since hello_xr works fine without the extension, I have no reason to think this would be a hardware problem. Debugging confirmed that the data being sent to the shaders regarding perspective and view matrices is the same in both apps. Validation layers do not report anything unusual.

Hardware used by the standalone version is an Oculus Quest 1; for the PCVR version, it is running in a MacOS desktop in Bootcamp, Windows 10, with the GPU being an AMD Radeon Pro Vega 48.

Unfortunately, I cannot imagine this as anything other than a software issue with OpenXR and/or its supporting components - this is why I would like to report the issue here. No workaround has been found so far.

**Comment by heriberto-delgado** [comment]
*sigh* never mind. It is, after all, a driver-or-lower-level issue. The app performs just fine in a laptop with Nvidia hardware - just recently verified. Feel free to close this issue at your earliest convenience.

**Comment by Izhido** [comment]
*sigh* Never mind. It is, after all, a driver-or-lower-level issue. The app performs just fine in a laptop with Nvidia hardware - just recently verified. Closing the issue as it never was an issue to begin with. Apologies for the inconvenience.
