### ISSUE TITLE
Is hmd screen 'low persistence' setting part of OpenXR?

### ISSUE THREAD

**Issue by Fredrum** [KhronosGroup/OpenXR-SDK-Source#296]
Hello!

I'm running the 'hello_xr' program and am getting ghosting on objects as I turn my head around and it reminds me of the old days before low persistence became a thing.
I'm doing this on a Raspberry Pi4b :)    (It was easier to get that running than PC-Ubuntu-NVidia)
And with a Oculus Rift CV1.

Is the on/off setting of the HMD screens' low persistence mode something that I should expect OpenXR to be able to take care of?

Cheers!

**Comment by rpavlik** [comment]
It should be done by the runtime or headset firmware. I assume you're using Monado? I'm not sure why you'd see ghosting, seems weird that Oculus would have low-persistence off by default, but I don't have a CV1 to test with.

**Comment by Fredrum** [comment]
Hi!  Yes correct guess I am using Monado. So you think the low-persistence setting would be already in a 'state' in the HMD firmware and unless changed it should reamin at the whatever setting?

EDIT:  I couldn't find any mentions of 'persistence' setting in the Monado source code so I assume it doesn't get set/changed by it?

When I'm running the hello_xr program in the Rift it now feels like I have a pretty good frame rate but it would be useful to get a confirmation of that.
The static blue square in the middle of the view that's locked to the head transform looks perfect no ghosting on that, but of course that's static relative to the view.

**Comment by rpavlik** [comment]
If your terminal isn't flooded with "frame missed" messages I think it's keeping up. In any case, let's continue this on the Monado Discord - see link at https://monado.freedesktop.org
