### ISSUE TITLE
How to implement xrGetReferenceSpaceBoundsRect?

### ISSUE THREAD

**Issue by Naomi-Kim** [KhronosGroup/OpenXR-SDK-Source#299]
Can you guide me how to implement xrGetReferenceSpaceBoundsRect? 

I didn't find anything generating any information about Boundary in specification.
Does BoundsRect mean the same as Guardian on Oculus device?
Please give me a hint on how I can provide BoundRect and the flow for XrEventDataReferenceSpaceChangePending.

**Comment by rpavlik** [comment]
Yes, that's roughly the idea: the bounds rect is the play area inside the guardian/chaperone/etc. If you have additional specific questions about the spec text for the event, feel free to file additional issues.
