### ISSUE TITLE
Build android version

### ISSUE THREAD

**Issue by Leon-Zhang** [KhronosGroup/OpenXR-SDK-Source#306]
Hello, I need to build openxr android version, but I didn't find Android.mk files etc which required to build with ndk, does openxr support android? Thanks in advance.

**Comment by utzcoz** [comment]
@Leon-Zhang This project use Gradle and CMake to build OpenXR Android build. You can run `./gradlew :src:tests:hello_xr:build` to build everything of this project shortly.

**Comment by Leon-Zhang** [comment]
@utzcoz Thanks very much for reply. I tried generate gradlew using `gradle wrapper` command, and then `./gradlew :src:tests:hello_xr:build` in root folder, but I get 
```
$ ./gradlew :src:tests:hello_xr:build

FAILURE: Build failed with an exception.

* What went wrong:
Project 'src' not found in root project 'OpenXR-SDK-Source'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```
How I can fix this? thanks.

**Comment by utzcoz** [comment]
@Leon-Zhang You can check https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/main/.github/workflows/android-helloxr-ci.yml#L23-L31 for CI building. I can confirm it works correctly.

**Comment by cuncaojin** [comment]
@Leon-Zhang There is no need to manually generate gradlew first and then use it to compile `hello-xr`. You just need to execute `./gradlew build` in the `hello-xr` directory.
```shell
~/OpenXR-SDK-Source/src/tests/hello_xr$ ./gradlew build
```
