### ISSUE TITLE
xrLocateSpace does not return valid poses for Valve Index controllers

### ISSUE THREAD

**Issue by calokat** [KhronosGroup/OpenXR-SDK-Source#316]
Hello,

When running the hello_xr sample with a Valve Index headset and Valve Index controllers, the controllers do not show up as cubes. This is likely because xrLocateSpace does not return an XrSpaceLocation with valid tracking for the hand spaces. The XrSpaceLocation parameter will have its locationFlags set to 0. 

I believe this is an issue with the Valve Index. I have built hello_xr for my Oculus Quest 1, and the controllers show up as cubes.

**Comment by 1runeberg** [comment]
Hi - sorry for the delay, I just tried to repro this using the latest steamvr stable release and unable to get any tracking issues:

![image](https://user-images.githubusercontent.com/17371351/182731207-91c58d62-3df4-4304-9f39-c4c8b30dc26f.png)

Can you share a system report?

![image](https://user-images.githubusercontent.com/17371351/182730730-e049ec4b-b588-4dbf-81f7-5a9dbfe443b9.png)

**Comment by calokat** [comment]
Hi @1runeberg , thank you for your reply and apologies for my delay. I pulled the latest commit from main this morning. The controllers are still not tracked. Attached is a system report.

[SteamVR-2022-08-26-AM_07_17_23.txt](https://github.com/KhronosGroup/OpenXR-SDK-Source/files/9432673/SteamVR-2022-08-26-AM_07_17_23.txt)

I am using SteamVR v1.23.7, and I am building the OpenXR-SDK-Source repo on Windows using Visual Studio, then running hello-xr as the startup project. Let me know what other details may help.

Many thanks.

**Comment by calokat** [comment]
Closing this, as I no longer have access to my Index, so I don't have a way to reproduce this even if this is still an issue.
