### ISSUE TITLE
Having trouble producing correct projection matrix.

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/OpenXR-SDK-Source#320]
Hi,

I am having trouble deriving a sane projection matrix from the fov values, the image appears badly separated in the HMD (which is extremely headache inducing!).

If I force a 'normal' 90deg projection per eye, things are much better but of course not ideal.

The fovAngle values I'm getting from OpenXR look a bit weird to me too, ie:

```
### eye 0 fov left -0.948912 right 0.894034 up 0.970919 down -0.975546 width 1.84295 height 1.94647
### eye 1 fov left -0.89655 right 0.947925 up 0.971726 down -0.974295 width 1.84448 height 1.94602
...repeating...
```
FIrst up, each eye has a different fov, which I can understand for x axis but not for y. Also width/height are different for each eye which also seems odd.

Are these fov numbers normal-ish?

I am using the 'local' reference space for everything.

I am polling for fov/pose everything frame.

I haven't managed to get hello_xr runnintg yet, I'll keep hacking at that though. I have been using it reference and as far as I can tell I'm doing the same things.

I'm using an HTC Vive 'classic' on Windows 10.

Finally, is this the right place to be asking questions like this? I can't find a 'general' OpenXR discussion board anywhere, just Unity/Unreal etc, while I'm using plain c++/opengl.

Bye!
Mark

**Comment by blitz-research** [comment]
hello_xr is running fine so it must be me...

**Comment by rpavlik** [comment]
Community.khronos.org has the discussion forum.
