### ISSUE TITLE
Android loader doc: Can support API >29 with workaround

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-SDK-Source#328]
A change was recently contributed to Monado to be able to lift the limitation of "must build for 29 or below" caused by having to use the package manager to find the runtime and load the Java code in the client/app process. Instead it now computes a path to the dex file and loads that directly.

The loader design doc currently calls out the 29 API limit because at the time I wasn't sure if a workaround existed. At the very least, that restriction can be removed, since we know it is possible, with Monado as an existence proof. A Monado contributor suggested mentioning how the workaround is done, so that other runtimes can do similarly, if required.

I wondered if it may be better to update the broker and its spec to have another path for the dex file, since the "find my dex based on my shared library" logic is not fully documented and is based on some assumptions/implementation details that may change. My thought was that runtimes could be kept running even after a platform change by having an updated broker, but I'm not sure that logic holds or makes sense.

See the discussion on the Monado gitlab here: https://gitlab.freedesktop.org/monado/monado/-/merge_requests/1476#note_1536766

**Comment by utzcoz** [comment]
@rpavlik If app uses OpenXR loader and targets its sdk to 30+(Android 11+), especially 32/33, the app also needs declare `query` or `android.permission.QUERY_ALL_PACKAGES` to bind Monado's service with https://gitlab.freedesktop.org/monado/monado/-/merge_requests/1476#note_1536766. I tested it on Pixel 3a XL with Android 12. Looks like there are extra work needed to be done to remove this restriction totally.

**Comment by rpavlik** [comment]
Yeah sorry I didn't update this issue, am aware of that. Think we are just going to use the same intent filter for runtime service as used for runtime discovery.

**Comment by utzcoz** [comment]
> Think we are just going to use the same intent filter for runtime service as used for runtime discovery.

Sounds great. `org.khronos.openxr.OpenXRRuntimeService` can be a great choice to use `query` in loader AAR because it is a contract defined in OpenXR Loader spec between loader and Runtime.

**Comment by rpavlik** [comment]
Confirmed that this plan works, parts are being reviewed now. Hoping we can get this (the loader AAR manifest change and loader doc/spec change) in the next release

**Comment by rpavlik** [comment]
This has been released in 1.0.28 (the query part anyway. Loading of classes is not documented but this should be easy to search for - haven't heard from others that this blocks them.)
