### ISSUE TITLE
Unclear semantics multiple for multiple HandTrackerEXT handles per hand

### ISSUE THREAD

**Issue by Wallbraker** [KhronosGroup/OpenXR-SDK-Source#330]
Is it allowed to create multiple `HandTrackerEXT` handles from [xrCreateHandTrackerEXT](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#xrCreateHandTrackerEXT) or not? The spec isn't clear.

**Comment by rpavlik** [comment]
The WG reports that in general, you can create as many handles of a type as you want, unless otherwise specified though you may hit a "limit reached" at some point. The WG declined to add additional language explicitly stating this.
