### ISSUE TITLE
How to collect audit logs for OpenXR applications

### ISSUE THREAD

**Issue by mshoaib6** [KhronosGroup/OpenXR-SDK-Source#333]
Hi! I’m working on a research project and want to know if I can use OpenXR in any way to extract audit logs for entity interactions, for instance, if an OpenXR application is interacting with a file (let’s say a browser application is trying to access a file stored in memory) or an application is trying to access a website to perform authentication (for instance, it’s trying to log into Facebook) etc. I would like to use these audit logs to understand the applications’ behavior. Your feedback would be appreciated! Thanks.

**Comment by rpavlik** [comment]
None of the interactions you mentioned go through OpenXR. There is an API dump layer but that will only give you information about the actual OpenXR calls, so things like VR/AR rendering, controllers, etc. I suspect you maybe have the wrong project or something?

**Comment by mshoaib6** [comment]
Thanks for your reply. I understand that I can only collect information through the API dump layer. I would like to ask if it's possible to somehow derive correlations between the information from API dump layer and the android debug bridge (adb) logs? For instance, the following is an adb log snapshot for the HelloXR app:
09-22 14:13:08.583   863  9967 D TrackingService: getSharedMemory: com.khronos.openxr.hello_xr.opengles, HeadTracker

Can I correlate this with the API dump layer logs automatically somehow rather than doing it manually (for instance, if the API dump layer logs have some piece of information (e.g. PID or some other unique ID) that is similar to the entries in the adb logs, it would be possible to correlate them automatically). Your help is much appreciated.

**Comment by rpavlik** [comment]
The API dump layer should be relatively easy to adapt to dump to logcat too
