### ISSUE TITLE
Issue building off of latest commit

### ISSUE THREAD

**Issue by jackdaus** [KhronosGroup/OpenXR-SDK-Source#338]
Hello, 

I'm new to OpenXR and trying to follow along with the Oculus Native development for OpenXR (https://developer.oculus.com/documentation/native/android/mobile-build-run-hello-xr-app/). 

As I was following along with these steps, I was having trouble building the hello_xr project. I was getting this build error:
```
Build command failed.
Error while executing process C:\Users\jackd\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C C:\Git\OpenXR\OpenXR-SDK-Source\src\tests\hello_xr\.cxx\Debug\4q165j76\armeabi-v7a XrApiLayer_api_dump XrApiLayer_core_validation hello_xr}
ninja: Entering directory `C:\Git\OpenXR\OpenXR-SDK-Source\src\tests\hello_xr\.cxx\Debug\4q165j76\armeabi-v7a'
[1/36] Generating C:/Git/OpenXR/OpenXR-SDK-Source/src/tests/hello_xr/.cxx/Debug/4q165j76/armeabi-v7a/include/openxr/openxr_reflection.h
FAILED: include/openxr/openxr_reflection.h 
cmd.exe /C "cd /D C:\Git\OpenXR\OpenXR-SDK-Source\src\tests\hello_xr\.cxx\Debug\4q165j76\armeabi-v7a\include\openxr && C:\Users\jackd\AppData\Local\Microsoft\WindowsApps\python3.exe C:/Git/OpenXR/OpenXR-SDK-Source/include/openxr/../../specification/scripts/genxr.py -registry C:/Git/OpenXR/OpenXR-SDK-Source/include/openxr/../../specification/registry/xr.xml -o C:/Git/OpenXR/OpenXR-SDK-Source/src/tests/hello_xr/.cxx/Debug/4q165j76/armeabi-v7a/include/openxr openxr_reflection.h"
'C:\Users\jackd\AppData\Local\Microsoft\WindowsApps\python3.exe' is not recognized as an internal or external command,
operable program or batch file.
```

I checked the path, and I indeed **do not** have Python3.exe located there.

This was when I was using the latest commit of this repo (b88b7e7c422a304d733854c4aef449d292ebc9e3). After checking out an older commit tagged `release 1.0.25` (15c3d8eb99994e5365d6b6f96eefaf4c51a65a9d), the error message did not occur on build. The build succeeded. 

Just wanted to give you a heads up in case this might be a new issue.

**Comment by rpavlik** [comment]
Hmm, it should have done it internally, do you have Python installed at all? Pretty surprised it apparentlly regressed... Does it still do it if you start with a fresh clone?

**Comment by jackdaus** [comment]
Huh, getting a fresh clone worked! Not sure why. I'm now able to build and run hello_xr from the latest commit of the repo (b88b7e7c422a304d733854c4aef449d292ebc9e3). Thanks!

**Comment by rpavlik** [comment]
Something was cached in the build tree, and Gradle puts build parts all over so it's easier to just clone again than to try to explain what all to remove.

**Comment by jackdaus** [comment]
Thanks for the explanation, I'm new to Gradle so I'm always looks to learn :)
