### ISSUE TITLE
CMake Error: Could not create named generator Visual Studio 16 Win64

### ISSUE THREAD

**Issue by tdbe** [KhronosGroup/OpenXR-SDK-Source#340]
Just trying to follow the [build readme](https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/main/BUILDING.md). I generally find it sparse in steps and details, especially things like this: "Finally, open the build\win64\OPENXR.sln in the Visual Studio to build the samples." -- confirm _how_ to build. Just click Build and it builds everything? 🙂 Which samples does it build and where do they go?

Anyway, this command is wrong: `cmake -G "Visual Studio [Version Number] Win64" ../..`
In windows 10 x64, with Visual Studio 2019 (16), if you write: `cmake -G "Visual Studio 16 Win64" ../..`
It says:
```
CMake Error: Could not create named generator Visual Studio 16 Win64

Generators
  Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Deprecated.  Generates Visual Studio 2010
                                 project files.  Optional [arch] can be
```

Confused because one place doesn't mention 2019 and the other doesn't mention Win64 or x64. Maybe guide should say `cmake -G "[cmake Generators list item]" ../..`

I managed to get it "working" with this command: `cmake -G "Visual Studio 16" x64 ../..` 
However I see a whole bunch of Failures:

```
C:\repos\openxr\OpenXR-SDK-Source\build\win64>cmake -G "Visual Studio 16" Win64 ../..
CMake Warning:
  Ignoring extra path from command line:

   "C:/repos/openxr/OpenXR-SDK-Source/build/win64/Win64"


-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/msys64/mingw64/bin/python3.exe (found suitable version "3.10.7", minimum required is "3")
-- Found OpenGL: opengl32
-- Enabling OpenGL support
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found JsonCpp: C:/msys64/mingw64/lib/cmake/jsoncpp
-- Enabling OpenGL support in hello_xr, loader_test, and conformance, if configured
-- Could NOT find glslc, using precompiled .spv files
-- Looking for secure_getenv
-- Looking for secure_getenv - not found
-- Looking for __secure_getenv
-- Looking for __secure_getenv - not found
-- Looking for timespec_get
-- Looking for timespec_get - found
-- Configuring done
-- Generating done
-- Build files have been written to: C:/repos/openxr/OpenXR-SDK-Source/build/win64
```

So not sure if it's as expected.

If I were you, I would actually have a tutorial-style build readme that shows feedback: like "write this command" and "here's the kind of output you should expect to see from that command". 🙂

**Comment by tdbe** [comment]
I found the solution on the khronos forums: https://community.khronos.org/t/building-openxr-sdk-with-visual-studio-2022-community-edition/108579 Strange this doesn't come up anywhere else on the internet except for that one post you have to manually search for.

_For VS 2019,2022 you no longer specify the architecture as part of the generator name, but with the -A command line argument:_
`cmake -G "Visual Studio 17 2022" -A x64 ..\.. `

As for the "could not find" / failures in the log, those should be fine, as was mentioned in that thread.

Now if only someone updated their readmes ;)

**Comment by tdbe** [comment]
I found confirmation on the khronos forums for the correct command through an example: https://community.khronos.org/t/building-openxr-sdk-with-visual-studio-2022-community-edition/108579 
_For VS 2019,2022 you no longer specify the architecture as part of the generator name, but with the -A command line argument:_
`cmake -G "Visual Studio 17 2022" -A x64 ..\.. `

As for the "could not find" / failures in the log, those should be fine, as was mentioned in that thread.

**Comment by rpavlik** [comment]
Yeah this is a caveat of having too much detail in the build instructions instead of referring folks to the CMake docs: https://cmake.org/cmake/help/latest/guide/user-interaction/index.html#guide:User%20Interaction%20Guide
