### ISSUE TITLE
Building samples with gcc (don't use .sln / MSVC / visual studio)

### ISSUE THREAD

**Issue by tdbe** [KhronosGroup/OpenXR-SDK-Source#341]
The building.md readme for windows says use cmake with visual studio to generate a .sln.

`Finally, open the build\win64\OPENXR.sln in the Visual Studio to build the samples.`

Is there any specific reason why this is tied to visual studio, MSVC, .sln's?

I would love to compile OpenXR-SDK-Source with just gcc. To integrate in non MSVC projects. But not sure if you can / what's the best way to do that

I can probably gcc the minimal version of the openxr sdk, but I want the samples etc :)

**Comment by tdbe** [comment]
Here's one path I've figured out, which successfully built the hello_xr.exe using `make` (without sln/MSVC). Anyone let me know if there's a simpler/better way. (and otherwise mark this as solved I guess)

---

I looked through the cmake generators list and chose MinGW Makefiles. So I ran:
`C:\repos\openxr\OpenXR-SDK-Source\build\win64\ cmake -G "MinGW Makefiles" ..\..`
because I already had MinGWx64 set up on my win machine.
([details here](https://stackoverflow.com/questions/51509173/how-can-i-make-cmake-use-mingw-w64-gcc-g))

This created `Makefile`'s in every subfolder where otherwise you would have gotten a .sln from the Visual Studio version of the command. Yes, it is weird to use MinGW (linux) to build windows executables, but we only used it to get the Makefiles.

Then you can use [chocolatey](https://chocolatey.org/install) to `choco install make`.

(then restart your cmd window if you had it open since before installing make)

Then run `C:\repos\openxr\OpenXR-SDK-Source\build\win64>make -f Makefile`
This root Makefile has info on all other Makefiles in the subfolders and will build everything (takes a while)

Then you have your exes. Make sure you run them from a cmd because they ask for parameters.

**Comment by tdbe** [comment]
Another way to build successfully, using Ninja:

`C:\repos\openxr\OpenXR-SDK-Source\build\win64\ cmake -GNinja ..\..`
and then
`ninja`
or specify `ninja hello_xr` fodler

I am pretty sure there isn't any visual studio specific shenanigans going on in the repo, I guess the build.md was just not including alternatives. Was confusing because it does mention you can also use vscode, but mentions building in it still via visual studio tools.

**Comment by rpavlik** [comment]
Yep, you can build with just about anything you like. This is just another thing like https://github.com/KhronosGroup/OpenXR-SDK-Source/issues/340 - I'm tempted to just delete that whole section of the docs and point to the CMake docs instead, because ours are outdated and unnecessariliy limited.

IIRC you can't target D3D with the samples in this repo under MinGW since some headers are only in the windows SDK, but vulkan and OpenGL should work fine. I personally am probably 70%/30% Linux/Windows usage, I believe our Linux CI tests both GCC and Clang. I don't think I merged the changes to add MinGW to our CI because I was trying to get all the features to work first, but you can probably start with my draft PR and adjust it to add it to the test matrix.

**Comment by tdbe** [comment]
> Yep, you can build with just about anything you like. This is just another thing like #340 - I'm tempted to just delete that whole section of the docs and point to the CMake docs instead, because ours are outdated and unnecessariliy limited.
> 
> IIRC you can't target D3D with the samples in this repo under MinGW since some headers are only in the windows SDK, but vulkan and OpenGL should work fine. I personally am probably 70%/30% Linux/Windows usage, I believe our Linux CI tests both GCC and Clang. I don't think I merged the changes to add MinGW to our CI because I was trying to get all the features to work first, but you can probably start with my draft PR and adjust it to add it to the test matrix.

ah amazing reply. Thanks for all that. Yeah I couldn't get D3D to work and was suspecting something like that.

You can delete the readme, but imo you should write something so users understand what is going on:
something like "you can compile with cmake, for any platform etc. For example visual studio msvc/sln, cmake, clang, ninja, mingw" 
And mention D3D.

I hadn't done this sort of thing in a while and needed a bit of hand holding 😊
