### ISSUE TITLE
Rendering glitches in DCS with Motion Reprojection

### ISSUE THREAD

**Issue by Aethedor** [KhronosGroup/OpenXR-SDK-Source#342]
I don't know if this is the right place to report this bug, so sorry if it's not. First, thank you very much for your work on OpenXR. I use VR often to play DCS (fighter jet flight simulator) and SteamVR is horribly unstable. Some releases are okay, others crash within minutes. So it is with the current SteamVR release. OpenXR allows me to continue flying in DCS. Big thanks!

I would use OpenXR all the time, but I have weird rendering issues with OpenXR. It only happens when I turn on Motion Reprojection.

In the F-16, you can have some of the information that is shown in the Head-Up Display (HUD) in front of you, be projected in your virtual helmet. That information stays in the center when you move your head. This works fine with SteamVR, but when I use OpenXR and I slowly move my head, the information shown in the center sort of drags the landscape behind it with it.

Look at this picture: https://1.bp.blogspot.com/-b-WzDk5eYQU/XZxNJ5iTWwI/AAAAAAAAF5M/YpkhDbJPdVYtQn--BNDQHtwQtii3Ir5BgCK4BGAYYCw/s1600/20191008170934_1.jpg On the right side is the HUD, in the center the information as projected on the pilot's helmet. That information follows my view. When I slowly move my head, those letters and numbers in the middle of the screen drag the grass fields and the trees behind it along with it. It looks / feels a bit like I'm finger painting the landscape with those letters and numbers.

If I knew how to make a video of it to show it to you, I would. This is the best way I can describe it (English not being my native language). I hope you can fix this, because it's quite annoying and without Motion Reprojection, it doesn't look really smooth. I really hope OpenXR can be a permanent SteamVR replacement for me, as I'm really done with that unstable software.

**Comment by Wallbraker** [comment]
We can't unfortunately not help you with this, you will need to file a issue with DCS and the OpenXR support in there.
