### ISSUE TITLE
Macro expansion producing "defined" has undefined behavior

### ISSUE THREAD

**Issue by Khrysys** [KhronosGroup/OpenXR-SDK-Source#343]
I was a little confused when I saw this at first, because when building with CMake on MSVC, it keeps popping up as a warning in ```winbase.h```. This shouldn't be to hard to fix, but also would be very low priority in the grand scheme of things. Simply replacing whatever line says ```defined``` with an ```#ifdef``` guard should fix this warning, and it only occurred once, so there shouldn't be any other issues relating to this.

Thanks.

**Comment by rpavlik** [comment]
I'm not sure what you mean, I haven't seen this warning, please paste the actual warning in here.

We do use `#if defined(XYZ)` instead of just `#ifdef XYZ` in several places because there may be more than one condition we have to test, but I've never seen a warning in winbase.h because of it.

**Comment by Khrysys** [comment]
@rpavlik Warning was found. There was no issue inside of this repository, it was found inside of `winbase.h`. One of the lines was `#define FOO defined(BAR)`, which caused the warning. Simple matter. Thanks for the help.

**Comment by rpavlik** [comment]
ah, ok, well then :) I did actually find an typo in one of the OpenXR headers, but presumably it wasn't the problem :)
