### ISSUE TITLE
Linking fails in path containing spaces

### ISSUE THREAD

**Issue by maluoi** [KhronosGroup/OpenXR-SDK-Source#344]
I keep my project in a folder containing spaces, so I can ensure my project doesn't have any of this type of error :) I normally build with `xmake` which builds in a cache folder, but when using `cmake` directly in my project folder, this does become an issue.

Specifically, the `--version-script` argument here is not surrounded by quotes, causing the path to split into two arguments.
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/b88b7e7c422a304d733854c4aef449d292ebc9e3/src/loader/CMakeLists.txt#L271

**Comment by rpavlik** [comment]
This should work now, thanks for the report! Fixed in 1.0.32.
