### ISSUE TITLE
About API Dump Layer

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/OpenXR-SDK-Source#348]
Hi!

I am working on a project and would like to see what kind of information/functions does API dump layer record? Is there a table or documentation you can refer me to?

Thanks!

**Comment by rpavlik** [comment]
See the README file for the API dump layer: https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/main/src/api_layers/README_api_dump.md

**Comment by ghost** [comment]
Hi! Thanks for your response before. I have another question. Can the API dump logs generated for every application that uses the OpenXR framework? Or can I just see the API dump for open-sourced applications?

**Comment by rpavlik** [comment]
It works for any application running against OpenXR (if it uses a loader which allows forcing on layers, which is all except maybe the Quest, as far as I know)
