### ISSUE TITLE
Is Vulkan 1.3 supported?

### ISSUE THREAD

**Issue by Onhi** [KhronosGroup/OpenXR-SDK-Source#369]
Looks like Vulkan 1.3 is not supported. (?)

xrGetVulkanGraphicsRequirements2KHR currently returns a maxApiVersionSupported of 0x0001000200000000 :(

**Comment by rpavlik** [comment]
This is a per-runtime thing, what runtime do you use?

Also, here's the description of that field:

> maxApiVersionSupported is the maximum version of Vulkan that the runtime has been tested on and is known to support. Newer Vulkan versions might work if they are compatible. 

So I would expect that vulkan 1.3 would work, just means the runtime hasn't explicitly tested and updated to reflect that testing.

**Comment by Onhi** [comment]
I use SteamVR and yes it works just fine. I guess it's just a bit confusing and I was really expecting it to crash.

**Comment by rpavlik** [comment]
great. Yeah, the fact that "max" means "max tested" while "min" means "almost certainly won't work below this" is a little weird. Would be nice if folks updated the max value too. I'll raise this with the WG.
