### ISSUE TITLE
Binding the action to the wrong path.

### ISSUE THREAD

**Issue by HandsomeXi** [KhronosGroup/OpenXR-SDK-Source#370]
I got from the spec that the click component is always a boolean value.

> click - A physical switch has been pressed by the user. This is valid for all buttons, and is common for trackpads, thumbsticks, triggers, and dpads. "click" components are always boolean.

But in the helloxr, it create a float action and bind it to a click path.
```
 Create an input action for grabbing objects with the left and right hands.
XrActionCreateInfo actionInfo{XR_TYPE_ACTION_CREATE_INFO};
actionInfo.actionType = XR_ACTION_TYPE_FLOAT_INPUT;
strcpy_s(actionInfo.actionName, "grab_object");
strcpy_s(actionInfo.localizedActionName, "Grab Object");
actionInfo.countSubactionPaths = uint32_t(m_input.handSubactionPath.size());
actionInfo.subactionPaths = m_input.handSubactionPath.data();
CHECK_XRCMD(xrCreateAction(m_input.actionSet, &actionInfo, &m_input.grabAction));


CHECK_XRCMD(xrStringToPath(m_instance, "/user/hand/left/input/select/click", &selectPath[Side::LEFT]));
CHECK_XRCMD(xrStringToPath(m_instance, "/user/hand/right/input/select/click", &selectPath[Side::RIGHT]));

XrPath khrSimpleInteractionProfilePath;
CHECK_XRCMD(xrStringToPath(m_instance, "/interaction_profiles/khr/simple_controller", &khrSimpleInteractionProfilePath));
std::vector<XrActionSuggestedBinding> bindings{{// Fall back to a click input for the grab action.
                                                            {m_input.grabAction, selectPath[Side::LEFT]},
                                                            {m_input.grabAction, selectPath[Side::RIGHT]},
```
I think this is ambiguous with the sepc, is this allowed?

**Comment by rpavlik** [comment]
This is allowed: if a float action is bound (whether thru suggested bindings or rebinding) to a boolean action, it is mapped with true = 1 and false = 0. 

> If the runtime is using the values provided by suggested bindings, it must make a best effort to convert the input value to the created action and apply certain rules to that use so that suggested bindings function in the same way across runtimes.

and 

> For actions created with XR_ACTION_TYPE_FLOAT_INPUT when the runtime is obeying suggested bindings: ... If the input value is boolean, the runtime must supply 0.0 or 1.0 as a conversion of the boolean value.

both in https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#input-suggested-bindings which is where all the "how to coerce/convert input" stuff is.

I do see that it's not actually explicit there that 1.0 is the true value, I'll make an issue to track that spec error.

**Comment by HandsomeXi** [comment]
@rpavlik Sorry, I didn't look carefully enough, thank you for your answer.
