### ISSUE TITLE
Wrong calling convention for layers on 32-bit Windows

### ISSUE THREAD

**Issue by SEt-t** [KhronosGroup/OpenXR-SDK-Source#378]
Loader expects `xrNegotiateLoaderApiLayerInterface`to use __stdcall convention for Win32 target:
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/15c3d8eb99994e5365d6b6f96eefaf4c51a65a9d/src/loader/api_layer_interface.cpp#L280
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/7450c5420789ff0ab63aaad2c4ed018807629a77/src/common/loader_interfaces.h#L78
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/7450c5420789ff0ab63aaad2c4ed018807629a77/include/openxr/openxr_platform_defines.h#L31

But layer's code specifies no calling convention:
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/ff3325c91a8a7c8bb6b3abcae1142bd166cc417f/src/api_layers/core_validation.cpp#L845
what results in use of default one (usually, __cdecl) and crash in loader due to convention mismatch.

**Comment by rpavlik** [comment]
This was fixed in 1.0.27!
