### ISSUE TITLE
Upload generated HelloXR files for all platforms to GitHub Actions artifacts

### ISSUE THREAD

**Issue by utzcoz** [KhronosGroup/OpenXR-SDK-Source#382]
Current GitHub Actions only update HelloXR's Android APK to GitHub Actions artifacts. But sometimes, developers/users want to use HelloXR for Windows platform likes me, and they don't want to build it locally, so they want to download built files from official GitHub Actions artifacts summary page, e.g. https://github.com/KhronosGroup/OpenXR-SDK-Source/actions/runs/4350122061.

If need, I can help to support this feature this weekend. cc @rpavlik .

**Comment by rpavlik** [comment]
Ah good idea. It is included in the (now badly named) openxr_windows_loader.zip release artifacts, FYI.

**Comment by utzcoz** [comment]
@rpavlik Thanks for you response. I think it is enough now, and I will check it.
