### ISSUE TITLE
User app crashes when no HMD is plugged

### ISSUE THREAD

**Issue by DaftMat** [KhronosGroup/OpenXR-SDK-Source#384]
Hello,

I use OpenXR 1.0.25 in C++ and SteamVR to render into an HMD. Everything was working fine until last SteamVR's update.

Since then, a call to `xrCreateInstance()` makes the app crash when no HMD is plugged.

Before then, it would not crash but instead return an unsuccessful XrResult enum type and let the app handle the problem.

Here is the call stack I get from the call to `xrCreateInstance()`, showing the unhandled exception coming from `vrclient_x64.dll`:
[![image](https://www.linkpicture.com/q/callstack.png)](https://www.linkpicture.com/view.php?img=LPic64148ef5255c220716562)

There is a [related issue on SteamVR's side](https://steamcommunity.com/app/250820/discussions/3/5219148331317637378/) which I commented with my situation. I am also opening this issue on OpenXR side just to be sure, if anything can be done on your end.

Thank you.

**Comment by etiennearnal** [comment]
I reproduced same issue after updating SteamVR from 1.24 to 1.25. 
@rpavlik is there a workaround ? or a better way to check if a HMD is plugged ?

**Comment by DaftMat** [comment]
SteamVR patched the issue on saturday 20/03/2023.
