### ISSUE TITLE
Does OpenXR SDK support macOS?

### ISSUE THREAD

**Issue by utzcoz** [KhronosGroup/OpenXR-SDK-Source#385]
After some investigation, I don't find macOS' supporting declaration from OpenXR spec and OpenXR-SDK-Source source code. Is there a plan to support macOS? Or is there any reason that OpenXR doesn't support macOS?

**Comment by lewa-j** [comment]
OpenXR is an open standard. The right question would be "Does macOS support OpenXR?"

**Comment by utzcoz** [comment]
@lewa-j Thanks. I updated the title to "Does OpenXR SDK support macOS"

**Comment by rpavlik** [comment]
If anyone is interested and able to specify OpenXR behavior on macOS, we would happily include that support. Nobody on the working group knows it well enough to specify it, and there are no runtimes I'm aware of, though some of the software should actually built on Mac. I think there might be a game engine that has a simulated runtime for development purposes on Mac.

**Comment by rpavlik** [comment]
The recently released 1.0.28 should build and work on macOS (if you have a suitable runtime). No mac-specific functionality (e.g. Metal support) is available at this time, but it should work roughly the same as Linux.
