### ISSUE TITLE
OpenXR xrGetSystem

### ISSUE THREAD

**Issue by OBess** [KhronosGroup/OpenXR-SDK-Source#391]
OS: Windows 10
Device: Oculus Quest 2
Runtime: Oculus
OpenXR version: 1.0.22
OpenXR-SDK-Source version built: 1.0.26 (because, I don't need eye tracking, and Oculus Quest 2 dosn't has it)

When I try to run openxr_runtime_list.exe, I get error: 
```
...
Info [GENERAL | xrCreateInstance | OpenXR-Loader] : ApiLayerInterface::LoadApiLayers succeeded loading layer XR_APILAYER_MBUCCHIA_toolkit using interface version 1 and OpenXR API version 1.0
Info [GENERAL | xrCreateInstance | OpenXR-Loader] : ApiLayerInterface::LoadApiLayers succeeded loading layer XR_APILAYER_LUNARG_core_validation using interface version 1 and OpenXR API version 1.0
...
Info [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance succeeded with 2 layers enabled and runtime interface - created instance = 0x0000514400000002
Verbose [GENERAL | xrCreateInstance | OpenXR-Loader] : Completed loader trampoline
[VALID_ERROR | VUID-XrSystemProperties-next-next | xrGetSystemProperties]: Invalid structure(s) in "next" chain for XrSystemProperties struct "next"
  Objects:
   [0] - XrInstance (0x0000514400000002)
[VALID_ERROR | VUID-xrGetSystemProperties-properties-parameter | xrGetSystemProperties]: Command xrGetSystemProperties param properties is invalid
  Objects:
   [0] - XrInstance (0x0000514400000002)
Failed to get system for HMD form factor.
```

How to fix it?

**Comment by erykpecyna** [comment]
Did you have Oculus Link enabled on the headset? It needs to be on and connected to the oculus app. The PC OpenXR runtime won't recognize the headset otherwise, giving you this "Failed to get system for HMD form factor" error because it doesn't see a headset.

**Comment by OBess** [comment]
> Did you have Oculus Link enabled on the headset? It needs to be on and connected to the oculus app. The PC OpenXR runtime won't recognize the headset otherwise, giving you this "Failed to get system for HMD form factor" error because it doesn't see a headset.

Yes, it was connected

**Comment by OBess** [comment]
The solution - https://community.khronos.org/t/xrgetsystemid-returns-error-code-2/109619/5
