### ISSUE TITLE
Integer version of XrExtent2D is signed

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-SDK-Source#4]
Negative extents make no sense.  `XrExtent2Di` should be `XrExtent2Du` and contain unsigned integer types.

**Comment by daveh-lunarg** [comment]
Hi @jherico,

This is the repository for various implementations of OpenXR functionality and code samples. The repository for the OpenXR specification itself is at https://github.com/KhronosGroup/OpenXR-Docs.

To bring your point to the attention of the spec authors, please submit it as an issue in the OpenXR-Docs repo.  Thanks!
