### ISSUE TITLE
input tracker poses.

### ISSUE THREAD

**Issue by TitansWhale** [KhronosGroup/OpenXR-SDK-Source#402]
I made my own trackers but I have absolutely no idea where to input the positions.

**Comment by rpavlik** [comment]
You will need to write your own runtime or integrate with an existing runtime (e.g. as a SteamVR driver): there is no OpenXR generic driver interface at this time. In some cases you can make an API Layer but it's less than ideal.

**Comment by TitansWhale** [comment]
> 您将需要编写自己的运行时或与现有运行时集成（例如作为 SteamVR 驱动程序）：此时没有 OpenXR 通用驱动程序接口。在某些情况下，您可以创建一个 API 层，但它并不理想。

thanks
