### ISSUE TITLE
Does Apple Vision Pro support?

### ISSUE THREAD

**Issue by notly** [KhronosGroup/OpenXR-SDK-Source#407]
Does Apple Vision Pro support OpenXR?

**Comment by rpavlik** [comment]
They are not currently listed as a conformant device, though it would be great if they did. Let Apple know that you expect OpenXR compatibility!

You can always see https://www.khronos.org/conformance/adopters/conformant-products/openxr for a list of conformant OpenXR products

**Comment by Merichbier** [comment]
@rpavlik Is it possible to get some insight information about the on-going discussion in the internal Khronos GitLab issue (for non-member) ?

**Comment by rpavlik** [comment]
In general, no, but there was no real discussion beyond what I had posted. Up to Apple's customers to demand OpenXR compatibility.
