### ISSUE TITLE
Validating conformance with registry.rnc

### ISSUE THREAD

**Issue by Plecra** [KhronosGroup/OpenXR-SDK-Source#408]
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/f122f9f1fc729e2dc82e12c3ce73efa875182854/specification/Makefile#L552-L557

How should `xr.xml` be validated against `registry.rnc`? This seems to be the only mention of `registry.rnc` in the repository, but neither checkXml.sh or registry/registry.rnc actually exist.

Relatedly, which `registry.rnc` file is `xr.xml` valid for? It's unclear which revision of the upstream Vulkan repository is meant to be used.

**Comment by Plecra** [comment]
Oh, I see, they're located in the OpenXR-Docs repo. https://github.com/KhronosGroup/OpenXR-Docs/tree/cc81ecbe6559ee3c6081d53e6670d00972deee72/specification/registry

Top, that's what I was looking for :) I probably missed some documentation about the relationships between these repos

**Comment by rpavlik** [comment]
Yeah, these are all derived from an internal monorepo, so sometimes the documentation is a bit awkward. I'm not sure if I ever put up the diagram showing how they fit together.
