### ISSUE TITLE
Opnexr in pico4

### ISSUE THREAD

**Issue by maohaotian** [KhronosGroup/OpenXR-SDK-Source#412]
Have anyone ever tried pico4 with openxr? I tried to run hello_xr example of pico4 in visual studio but I failed. Can anyone offer me a tutorial of this?

**Comment by korejan** [comment]
@maohaotian I think Pico's OpenXR runtime is still not compatible with the cross-vendor android loader so they provide their own vendor specific loader shared libs. If you go [here](https://developer-global.pico-interactive.com/sdk?deviceId=1&platformId=3&itemId=11) and download their OpenXR SDK, in the samples folder there is a modified version of hello_xr in there.

note the changelogs on that page first.

**Comment by rpavlik** [comment]
Hmm, that's disappointing. It's supposed to be compatible. I wonder if it just needs extra manifest entries like the quest does right now?

**Comment by korejan** [comment]
It may have changed recently in beta PUIs but i have yet to test it, they do require a different manifest [entry](https://developer-global.pico-interactive.com/document/native/openxr-sdk-quickstart/)

**Comment by maohaotian** [comment]
Thank you all! I fixed this via Android Studio. There is always something wrong when I try it with VS. I can continue my work now. Thanks again!
