### ISSUE TITLE
Launching, but not installing to Quest 2

### ISSUE THREAD

**Issue by jpswart82** [KhronosGroup/OpenXR-SDK-Source#418]
Hi,  I'm completely new to development for quest, and would like to start my introduction with this basic hello_xr app.  I am in developer mode, and using a fresh install of Android Studio, and a fresh install of python 3.11, on a Windows 10 machine with an intel i7.

The build succeeds, but installation does not - see error below.  Any help will be appreciated.

07/26 15:41:04: Launching 'hello_xr' on Oculus Quest 2.
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

List of apks:
[0] 'C:\xrkoos\OpenXR-SDK-Source-main\OpenXR-SDK-Source-main\src\tests\hello_xr\build\intermediates\apk\OpenGLES\debug\hello_xr-OpenGLES-debug.apk'
Installation failed due to: 'Failed to commit install session 624331105 with command package install-commit 624331105. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl624331105.tmp/base.apk (at Binary XML file line #37): intent tag may have at most one action.'
Retry
Failed to launch an application on all devices

**Comment by rpavlik** [comment]
Yes, this is a known issue, we will have a release out in a day or so to fix it. Although, I believe the quest still requires additional entries to be added to the manifest that are not in standard OpenXR.

**Comment by jpswart82** [comment]
Hi! Thank you for the diligent effort! 

When you say its a known issue, do you mean a long standing one? Did I misunderstand - is this hello_xr not specifically for quest?

and is there perhaps something I should be doing that I am not? 

Also, is there someplace (other than github) where I can look for information to develop specifically for the quest? Everything I've tried so far has not run (presumably because it is all outdated), this is the first source data that actually built successfully.

**Comment by rpavlik** [comment]
No, this is a known issue as in a bug added in the latest release that I've not had a chance to do the hotfix release fixing it.

Quest has not used the standard loader until recently, so the hello_xr in here has never worked unmodified on Quest, you have needed to go to the Oculus dev pages for instructions.

**Comment by rpavlik** [comment]
OK, the hotfix source is up. (Binaries aren't up yet but you aren't using them if you're just building hello_xr in-tree.

I believe for right now, you need to still add this to the manifest inside the `<activity></activity>` tags to run on the Quest 2 and related devices:

```xml
            <!-- Quest-specific intent filter -->
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="com.oculus.intent.category.VR" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
```

This is not optimal and will hopefully not be required in the future, which is why it isn't in the releases.

**Comment by jpswart82** [comment]
Thanks again, thank you very much!

Perhaps just as a note to you - I did not have to add anything to the manifest when running from Android Studio, it just worked on my quest 2 without any issues.  The first time I tried to run it it did give me some issues, but I had forgotten to allow access from my computer in the headset - once I clicked allow the launch happened automatically.

**Comment by rpavlik** [comment]
oh really?! That would be awesome. Now I have to try that here :)

**Comment by rpavlik** [comment]
ok, so I can start it up with adb, but it doesn't show up in the launcher yet. That's halfway there, I guess :)
