### ISSUE TITLE
OpenXR::headers not found when building loader disabled

### ISSUE THREAD

**Issue by pfontain** [KhronosGroup/OpenXR-SDK-Source#419]
When building the loader is disabled via the option in src/CMakeLists.txt, which is part of the Quest hello XR instructions https://developer.oculus.com/documentation/native/android/mobile-build-run-hello-xr-app/ , OpenXR::headers is not recognized because the loader CMakeLists.txt is never included. I ended up reverting some of the recent changes to make it work for now https://github.com/pfontain/OpenXR-SDK-Source/commit/cacade014b0e6db9b95f1f922ee5d2e0021e00ec

**Comment by rpavlik** [comment]
This should work now, thanks for the report! Fixed in 1.0.32.
