### ISSUE TITLE
SDK won't build using embedded python

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/OpenXR-SDK-Source#42]
The existing SDK CMake code uses python to generate a number of artifacts, but also uses the `PYTHONPATH` environment variable to ensure that common modules can be loaded.  

However, while trying to create an [openxr port for vcpkg](https://github.com/microsoft/vcpkg/pull/6339), I've discovered that vcpkg provides an embedded version of python.  Embedded versions of python from version 3.5.1 and on ignore the `PYTHONPATH` variable and this is apparently [by design](https://bugs.python.org/issue28245).  

I'm investigating what needs to happen to make the OpenXR build work with either a conventional Python3 installation or an embedded one.

**Comment by rpavlik** [comment]
I see you had patches in your vcpkg fork - I'd accept them.

**Comment by jherico** [comment]
I've opened a PR for the embedded python issue with #46 but I consider the other patch to be a pack, since it hard-codes library names.  However I can update my existing PR #44 to use a similar approach but use the `find_package(X11)` mechanism for the libraries instead of hard-coding them.

**Comment by rpavlik** [comment]
That would be great if you updated to use find modules. I merged the other PR.
