### ISSUE TITLE
[1.0.28] building without api layers result in cmake error

### ISSUE THREAD

**Issue by farmboy0** [KhronosGroup/OpenXR-SDK-Source#422]
Cmake option -DBUILD_API_LAYERS=no
The error is:
CMake Error at src/tests/loader_test/CMakeLists.txt:26 (add_dependencies):
  The dependency target "XrApiLayer_api_dump" of target "loader_test" does
  not exist.

With api layers the build is fine.

Build log from Gentoo:
[openxr-1.0.28:20230822-143346.log](https://github.com/KhronosGroup/OpenXR-SDK-Source/files/12409942/openxr-1.0.28.20230822-143346.log)

**Comment by rpavlik** [comment]
We found this internally as well. It should be resolved in 1.0.29, just released: the loader test will be skipped if the layers are disabled.
