### ISSUE TITLE
Failed to run hello_xr with ERROR [comp_window_direct_acquire_xlib_display]

### ISSUE THREAD

**Issue by changsheng230** [KhronosGroup/OpenXR-SDK-Source#433]
Run hello_xr with following command line:

 XR_RUNTIME_JSON=~/src/monado/build/openxr_monado-dev.json /usr/local/bin/hello_xr -g OpenGL

It ended up with the following errors:

ERROR [comp_window_direct_acquire_xlib_display] vkAcquireXlibDisplayEXT: VK_ERROR_UNKNOWN (0x00005640e3c6c0d0)
ERROR [compositor_init_swapchain] Window init_swapchain failed!
ERROR [comp_main_create_system_compositor] Failed to init compositor 0x5640e3c91070
XR_ERROR_INITIALIZATION_FAILED in xrCreateInstance: Failed to create the system '-3'
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance chained CreateInstance call failed
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed

More logs can be found at [hello_xr_logs.txt](https://github.com/KhronosGroup/OpenXR-SDK-Source/files/13257498/hello_xr_logs.txt)

**Comment by Wallbraker** [comment]
This is related to Monado, and probably because the display isn't properly marked as `non-desktop`.
