### ISSUE TITLE
How to access XR_ML_marker_understanding?

### ISSUE THREAD

**Issue by ablueatworld** [KhronosGroup/OpenXR-SDK-Source#435]
I have been trying to access XR_ML_marker_understanding since Magic Leap has added this extension to their latest release of their OXR samples. However, I have been unable to load and initialise any function pointers successfully. The openxr.h also lacks the definitions related to this extension.

I have tried building the latest OpenXR-SDK (version 1.0.31) with all the extensions enabled. However, even that was not a solution. Is there a way to build OpenXR with support for new ML extensions? And, will it be added to the Standard OpenXR Loader library?As you may know, on their website, Magic Leap recommends using the standard OpenXR Loader Lib.

I appreciate any help in this regard.

**Comment by Perksey** [comment]
cc @rbessems this appears to be missing from the registry, and grep.app didn't pull up any other references to this extension.

**Comment by rpavlik** [comment]
I think it's coming in 1.0.32 which will be out any day now.

**Comment by ablueatworld** [comment]
Thank you so much for your reply.

**Comment by rpavlik** [comment]
This is in 1.0.32, just released!
