### ISSUE TITLE
Exported symbols from loader

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-SDK-Source#45]
When reviewing the loader docs, I decided to dump the list of exported symbols from the loader, when built as a dynamic library on Windows. More than I expected showed up - in particular, note the first few:

- `_LoaderGenTermXrResultToString@16`
- `_LoaderGenTermXrStructureTypeToString@16`
- `_LoaderXrTermCreateApiLayerInstance@12`
- `_LoaderXrTermCreateDebugUtilsMessengerEXT@16`
- `_LoaderXrTermCreateInstance@8`
- `_LoaderXrTermDestroyDebugUtilsMessengerEXT@8`
- `_LoaderXrTermDestroyInstance@8`
- `_LoaderXrTermGetInstanceProcAddr@16`
- `_LoaderXrTermSetDebugUtilsObjectNameEXT@12`
- `_LoaderXrTermSubmitDebugUtilsMessageEXT@28`
- `_xrAcquireSwapchainImage@16`
- `_xrApplyHapticFeedback@20`
- `_xrBeginFrame@12`
- `_xrBeginSession@12`
- `_xrConvertTimeToTimespecTimeKHR@20`
- `_xrConvertTimeToWin32PerformanceCounterKHR@20`
- `_xrConvertTimespecTimeToTimeKHR@16`
- `_xrConvertWin32PerformanceCounterToTimeKHR@16`
- `_xrCreateAction@16`
- `_xrCreateActionSet@16`
- `_xrCreateActionSpace@16`
- `_xrCreateDebugUtilsMessengerEXT@16`
- `_xrCreateInstance@8`
- `_xrCreateReferenceSpace@16`
- `_xrCreateSession@16`
- `_xrCreateSwapchain@16`
- `_xrDestroyAction@8`
- `_xrDestroyActionSet@8`
- `_xrDestroyDebugUtilsMessengerEXT@8`
- `_xrDestroyInstance@8`
- `_xrDestroySession@8`
- `_xrDestroySpace@8`
- `_xrDestroySwapchain@8`
- `_xrEndFrame@12`
- `_xrEndSession@8`
- `_xrEnumerateApiLayerProperties@12`
- `_xrEnumerateEnvironmentBlendModes@28`
- `_xrEnumerateInstanceExtensionProperties@16`
- `_xrEnumerateReferenceSpaces@20`
- `_xrEnumerateSwapchainFormats@20`
- `_xrEnumerateSwapchainImages@20`
- `_xrEnumerateViewConfigurationViews@32`
- `_xrEnumerateViewConfigurations@28`
- `_xrGetActionStateBoolean@20`
- `_xrGetActionStatePose@20`
- `_xrGetActionStateVector1f@20`
- `_xrGetActionStateVector2f@20`
- `_xrGetBoundSourcesForAction@20`
- `_xrGetCurrentInteractionProfile@20`
- `_xrGetD3D10GraphicsRequirementsKHR@20`
- `_xrGetD3D11GraphicsRequirementsKHR@20`
- `_xrGetD3D12GraphicsRequirementsKHR@20`
- `_xrGetInputSourceLocalizedName@36`
- `_xrGetInstanceProcAddr@16`
- `_xrGetInstanceProperties@12`
- `_xrGetOpenGLGraphicsRequirementsKHR@20`
- `_xrGetReferenceSpaceBoundsRect@16`
- `_xrGetSystem@16`
- `_xrGetSystemProperties@20`
- `_xrGetViewConfigurationProperties@24`
- `_xrGetVisibilityMaskKHR@24`
- `_xrGetVulkanDeviceExtensionsKHR@28`
- `_xrGetVulkanGraphicsDeviceKHR@24`
- `_xrGetVulkanGraphicsRequirementsKHR@20`
- `_xrGetVulkanInstanceExtensionsKHR@28`
- `_xrLocateSpace@28`
- `_xrLocateViews@28`
- `_xrPathToString@28`
- `_xrPerfSettingsSetPerformanceLevelEXT@16`
- `_xrPollEvent@12`
- `_xrReleaseSwapchainImage@12`
- `_xrResultToString@16`
- `_xrSessionBeginDebugUtilsLabelRegionEXT@12`
- `_xrSessionEndDebugUtilsLabelRegionEXT@8`
- `_xrSessionInsertDebugUtilsLabelEXT@12`
- `_xrSetDebugUtilsObjectNameEXT@12`
- `_xrSetInteractionProfileSuggestedBindings@12`
- `_xrStopHapticFeedback@16`
- `_xrStringToPath@16`
- `_xrStructureTypeToString@16`
- `_xrSubmitDebugUtilsMessageEXT@28`
- `_xrSyncActionData@16`
- `_xrThermalGetTemperatureTrendEXT@24`
- `_xrWaitFrame@16`
- `_xrWaitSwapchainImage@12`

cc @daveh-lunarg

**Comment by daveh-lunarg** [comment]
Planning to switch this to a VisStudio .def file, rather than in-line decorations. It'll be a few weeks before I have time to look at it.

**Comment by brycehutchings** [comment]
I think it could be solved either way. With in-line decorations, we just need to be careful to not use the macro with declspec(export) on things that shouldn't be exported (the ones at the top of Ryan's list starting with 'Loader')

**Comment by rpavlik** [comment]
The inline decorations would also keep things consistent across platforms.

**Comment by daveh-lunarg** [comment]
Also, need to do the same export check on the API layers projects.

**Comment by daveh-lunarg** [comment]
I've had some difficulty getting this right with inline decorations, mostly due to some of the fxn declarations being in code-gen'd header files.  Adding a .def file is slam-dunk easy but doesn't do anything for the linux exports, so I'll take another run at in-lining it.

**Comment by daveh-lunarg** [comment]
WIP branch daveh-loader-exports-redux

**Comment by rpavlik** [comment]
We're only exporting core functions, right? There's a check at the beginning of the loop through the functions where it figures out if it's core, an extension that's just starting, or an existing extension. Could probably set a "export prefix" variable there (to the export macro or empty string) and use it in the replace later. (On phone so this is all from memory but I'm pretty sure this is the easiest way to do that.)

**Comment by rpavlik** [comment]
OK, I've got two approaches here done and ready for discussion by wg

**Comment by daveh-lunarg** [comment]
WG consensus was to go with 'core-only' export for now, with an eye towards restricting to the minimal set of 4 in the future (possibly with some additional extension-wrangling helpers).   PR #98 is approved, closing this issue.
