### ISSUE TITLE
Android: loader can't find libopenxr_forwardloader.so library as it is inside .apk

### ISSUE THREAD

**Issue by OpilkiInside** [KhronosGroup/OpenXR-SDK-Source#460]
Some devices may include .so file inside apk. For example, on Quest 3 v62, the following path is reported by the broker:

`/system/priv-app/VrDriver/VrDriver.apk!/lib/arm64-v8a/libopenxr_forwardloader.so`

`FileSysUtilsPathExists` won't be able to locate this file thus `RuntimeManifestFile::CreateIfValid` will fail with `does not appear to exist` message.

A simple fix would be to check if there's "!" symbol in the path, and just check the file before that symbol, essentially checking that `/system/priv-app/VrDriver/VrDriver.apk` exists.

**Comment by rpavlik** [comment]
This should be fixed in the 1.0.34 loader, have you tried that?

**Comment by OpilkiInside** [comment]
Confirming it is fixed in 1.0.34

I was following openxr-tutorial.com and it had a version with this bug, might be worth updating this on the website.

**Comment by utzcoz** [comment]
@rpavlik I sent a PR to update the version of tutorial, see https://github.com/KhronosGroup/OpenXR-Tutorials/pull/122.

**Comment by rpavlik** [comment]
yep 1.0.34 is a very recently release so the tutorial update not happening yet doesn't surprise me. Thanks @utzcoz for the PR, I'll go take a look and merge it.
