### ISSUE TITLE
OpenXR-SDK doesn't build on armv6

### ISSUE THREAD

**Issue by FriederHannenheim** [KhronosGroup/OpenXR-SDK-Source#465]
I am packaging OpenXR-loader for Void Linux and I noticed this. Please add armv6 to platform_utils.hpp

**Comment by rpavlik** [comment]
I literally just merged a fix for this, this past week. https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/464  Does main work for you?

**Comment by rpavlik** [comment]
Fix is now included in a release, 1.1.36.
