### ISSUE TITLE
Failed to distinguish different HMDs

### ISSUE THREAD

**Issue by rhzxg** [KhronosGroup/OpenXR-SDK-Source#466]
Given that OpenXR no longer provides controller model initialization, I need to init the models in case of different types of HMDs.
For example, when it comes to vive pro2 and vive focus 3, the code below can not distinguish them from each other.

 `XrSystemProperties systemProperties = {XR_TYPE_SYSTEM_PROPERTIES};
xrGetSystemProperties(xr_instance, xr_system_id, &systemProperties);
cout << systemProperties.systemName << endl; `

The [systemName] returned the same value: "Vive OpenXR: Vive SRanipal"

What do I do if I want to get the right HMD information?

**Comment by rpavlik** [comment]
https://github.com/KhronosGroup/OpenXR-Guide/blob/main/chapters/goals_design_philosophy.md#how-do-i-find-out-which-controller-is-in-use
