### ISSUE TITLE
How to implement function such like xrGetCurrentTime( )?

### ISSUE THREAD

**Issue by sockyjam** [KhronosGroup/OpenXR-SDK-Source#483]
In some case, I need to get the current time of XrTime, to get the current pose of HMD.

**Comment by rpavlik** [comment]
This is intentionally not provided, there is no reason a normal app would need the "current" pose. Use the predicted display time instead, for most purposes. Otherwise you are likely to introduce judder or other artifacts.

**Comment by sockyjam** [comment]
Thanks for reply.

**Comment by sockyjam** [comment]
@rpavlik thanks for reply. I see now. Please forget "current pose". Is there any function I can get the current time for some application reason?

**Comment by lewa-j** [comment]
xrWaitFrame -> XrFrameState -> predictedDisplayTime
