### ISSUE TITLE
Xcode 1.5 is not supported

### ISSUE THREAD

**Issue by Resident-Fortress** [KhronosGroup/OpenXR-SDK-Source#484]
Hi, I am trying to use the OpenXR-SDK-Source to compile a custom version of OpenXR for macOS Sequoia. Whenever I attempt to run "cmake -G "Xcode" ../.." I just get this output:

╭─User at User’s iMac Pro in /Volumes/InteliSense/Side Projects/OpenXR-SDK-Source/build/macos on main✔
╰─± cmake -G "Xcode" ../..
CMake Error:
  Xcode 1.5 not supported.

CMake Error: Could not create named generator Xcode

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  Xcode                        = Generate Xcode project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files
                                 (deprecated).
  CodeLite - Ninja             = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Unix Makefiles    = Generates CodeLite project files
                                 (deprecated).
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Kate - Ninja                 = Generates Kate project files (deprecated).
  Kate - Ninja Multi-Config    = Generates Kate project files (deprecated).
  Kate - Unix Makefiles        = Generates Kate project files (deprecated).
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).

╭─User at User’s iMac Pro in /Volumes/InteliSense/Side Projects/OpenXR-SDK-Source/build/macos on main✔
╰─±

**Comment by rpavlik** [comment]
This sounds like a cmake issue, not specific to this project. Try the unix makefiles or Ninja generator instead of xcode - they're command line builds but not as subject to the changing whims of Apple

**Comment by Resident-Fortress** [comment]
Sounds good. I'll test out the recommendation and close this ticket. Thanks for the help.
