### ISSUE TITLE
Problem when using multilayer in SteamVR Runtime + OpenXR SDK

### ISSUE THREAD

**Issue by sockyjam** [KhronosGroup/OpenXR-SDK-Source#488]
In helloxr application, if there's only one layer, everything is ok.
But when I add another layer to the application, the view is wrong.

Expect:
![image](https://github.com/user-attachments/assets/00f6fdeb-86e4-42c0-908a-9c2dbc1240ee)

But the result I got:
![image](https://github.com/user-attachments/assets/872b3c2b-4eea-4d3b-8918-d7c0eddf7be0)

I assign the same pose value to these two layers, so I suppose they should be the same action.
Did anyone meet the same problem? How to fix it?

**Comment by nnuber** [comment]
Thanks for reporting this issue. For bugs specific to SteamVR, please submit a bug report on the SteamVR OpenXR forums: https://steamcommunity.com/app/250820/discussions/8/

The SteamVR team does not monitor the Khronos GitHub for bugs or feature requests.

**Comment by ChristophHaag** [comment]
Just out of curiosity, those are 2 projection layers, not quad layers, right?

**Comment by sockyjam** [comment]
> Just out of curiosity, those are 2 projection layers, not quad layers, right?

Yes, 2 projection layer (XR_TYPE_COMPOSITION_LAYER_PROJECTION).

**Comment by sockyjam** [comment]
> Thanks for reporting this issue. For bugs specific to SteamVR, please submit a bug report on the SteamVR OpenXR forums: https://steamcommunity.com/app/250820/discussions/8/
> 
> The SteamVR team does not monitor the Khronos GitHub for bugs or feature requests.

thanks, I will copy it there.

**Comment by lewa-j** [comment]
Looks like SteamVR Beta Updated - 2.8.1 may fix it.

> Fix non-base projection layers displaying in the wrong space.

**Comment by ChristophHaag** [comment]
Confirmed fixed here https://steamcommunity.com/app/250820/discussions/8/4515506143569094001/#c4758703722108901886
