### ISSUE TITLE
LoaderInstance::CreateInstance, no support found for requested extension: XR_KHR_opengl_enable

### ISSUE THREAD

**Issue by csunking** [KhronosGroup/OpenXR-SDK-Source#499]
`./hello_xr -g OpenGL -ff Hmd -vc Stereo -bm AlphaBlend -s View` running bug found,  logs are:
```
[18:05:17.377][Info   ] Press any key to shutdown...
[18:05:17.378][Info   ] Available Layers: (0)
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance, no support found for requested extension: XR_KHR_opengl_enable
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : xrCreateInstance failed
Segmentation fault (core dumped)
```

**Comment by ChristophHaag** [comment]
That sounds like an OpenXR runtime issue, specifically that the runtime doesn't support for OpenGL applications. Which OpenXR runtime is this with?

**Comment by csunking** [comment]
Thanks, you are right, runtime should be set correctly and like this:
`export XR_RUNTIME_JSON=/home/xxxxxxxx/monado/build_install/share/openxr/1/openxr_monado.json`
