### ISSUE TITLE
OpenXR doesn't support acceleration and angularAcceleration

### ISSUE THREAD

**Issue by rmaroy** [KhronosGroup/OpenXR-SDK-Source#503]
Hi,

Hardware providers rely more and more on OpenXR. However, **OpenXR does not support acceleration and angularAcceleration input** (not velocity derived), which are, as position and orientation, key inputs of XR devices and tha are available for many headset products on the market. Accelerations and AngularAccelerations are the only vectors which are available when the handler are not visible by the headset. As such, they allow for the estimation of the movement when the disappearance of the handlers are momentary.

**
![UnrealEngine 5 4 4 Right Hand linear and angularAcceleration are (0, 0, 0)](https://github.com/user-attachments/assets/4188b5c4-e8bf-4db5-8bcb-7a2644b8e207)
![UnityVersion 2021 3 0f1 with Right Controler linear and angular accelerations return always (0, 0, 0)](https://github.com/user-attachments/assets/3790d29f-5b01-4f94-b12e-cf85e40f8906)** ? This lack is a major issue since, at the present time, there is no other way to get this informations.

Best Regards

**Comment by rpavlik** [comment]
Closing as a dupe to the other one I replied  to. (#504 )
