### ISSUE TITLE
hello_xr: Asymmetric FOV Angles Are Not Handled Correctly

### ISSUE THREAD

**Issue by Joel-Valenciano** [KhronosGroup/OpenXR-SDK-Source#515]
While working on a PS VR2 driver for Monado, I added asymmetric horizontal fov angles, to match the lenses' slightly offset autocollimation point.

I noticed that the runtime's reported fov for the right view does not seem to affect the resulting projection as expected, and it seems to mostly be affected by the left view's fov, with results similar to the attached image.

Swapping the signs on just the left view's horizontal fov angles causes the opposite effect: the right view will appear centered, while the left will be distorted.

Additionally, the right view will sometimes glitch between two different perspectives when moving the mouse, depending on the values used.

This issue does not seem to affect xrgears or SteamVR dashboard, which is why I think it might be an issue with hello_xr.

![fov](https://github.com/user-attachments/assets/58906106-9921-46d7-8224-6648c8fbd6a0)

**Comment by rpavlik** [comment]
Does this still happen if you use the compute compositor in Monado?

**Comment by Joel-Valenciano** [comment]
You were right, it does not happen with the compute compositor. Should I close this issue?

**Comment by rpavlik** [comment]
Yep, think so, think it's a Monado bug: https://gitlab.freedesktop.org/monado/monado/-/issues/444

May still be a hello_xr bug but not thinking so right now.

**Comment by Joel-Valenciano** [comment]
Yeah, that's probably true; I looked through hello_xr's source, and it looks like it generates the projections separately and gets the right values from xrLocateViews, even when it's drawn the wrong way.
