### ISSUE TITLE
Verify or fix std::map bracket operator insertions

### ISSUE THREAD

**Issue by daveh-lunarg** [KhronosGroup/OpenXR-SDK-Source#53]
There are a few instances in the loader code where a std::map is accessed via bracket operator
```
foo = map[key]
```
where it appears uncertain whether the key already exists in the map.  These should be changed to or guarded by .find() operations, to prevent an inadvertent insertion of the key into the map.

Tracks WG gitlab issue # [943](https://gitlab.khronos.org/openxr/openxr/issues/943)

**Comment by rpavlik** [comment]
Had to revert #55 since it broke 32-bit builds.

```
..\src\loader\runtime_interface.cpp(205): error C2440: 'initializing': cannot convert from 'nullptr' to 'XrInstance'
..\src\loader\runtime_interface.cpp(205): note: A native nullptr can only be converted to bool or, using reinterpret_cast, to an integral type
```

Please update and merge again.

**Comment by daveh-lunarg** [comment]
I'll try to repro here and fix -  is this on gcc or clang?

**Comment by rpavlik** [comment]
MSVC, 32-bit, on appveyor

**Comment by rpavlik** [comment]
Think it should just be replacing that nullptr with XR_NULL_HANDLE, not sure if there are others.
