### ISSUE TITLE
Need CI

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-SDK-Source#59]
We need 64-bit and 32-bit CI. We can do AppVeyor for 32-bit Windows CI, same basic layout as internal, but for main/Linux CI we'll need to set up something else (travis?)

Opening this mostly as a reminder to self, though anyone is welcome to set it up first and beat me to it :)

cc @outofcontrol @daveh-lunarg

**Comment by daveh-lunarg** [comment]
Just came here to create the same issue. 

I can spend some time on a Travis script eventually, but probably won't have time for a couple weeks. Would be very happy if you beat me to it 😃 .

**Comment by rpavlik** [comment]
OK, we now have azure-pipelines set up to do things as well as they're done internally (same build env, etc) 

Once we're satisfied we can probably stop using AppVeyor for this repo, given that it's so slow...
