### ISSUE TITLE
excepción de Microsoft C++: wxr::XrResultException en la ubicación de la memoria 0x0000004B1712EB90.

### ISSUE THREAD

**Issue by JulianConesa** [KhronosGroup/OpenXR-SDK-Source#78]
When running the samples_win32 program, Windows Mixed Reality does not start even though Mixed Reality OpenXR Runtime indicates that it is installed and active.

At the end of the execution it indicates the following error:

Exception produced in 0x00007FFFBE2F9129 in BasicXrApp_win32.exe: Microsoft C ++ exception: wxr :: XrResultException in memory location 0x0000004B1712EB90.

For what is this?
Can you help me?

**Comment by rpavlik** [comment]
Closing due to lack of response (and substantial updates to the mentioned runtime since then)
