### ISSUE TITLE
how to use Extension?

### ISSUE THREAD

**Issue by SlimSnow** [KhronosGroup/OpenXR-SDK-Source#83]
Extension is a library?Or a interface implement by myself.In the document The OpenXR Specification Chapter 12 List of Extensions.These Extensions all ready exist in my system?If all ready exist,where are there?How to use these Extensions all ready exist and how to "develop" myself Extensions ?

**Comment by rpavlik** [comment]
Any number of extensions may be supported by your runtime. You need at least one extension (a graphics binding extension) to make an application. To access the features of an extension, you pass its name in your `XrInstanceCreateInfo` structure to `xrCreateInstance`. On the simplest level - if the extension isn't available, that call will fail. (You may use `xrEnumerateInstanceExtensions` to find out what extensions are supported)

**Comment by SlimSnow** [comment]
@rpavlik Thank you for your advise.I use the samples In this project. Start with the arguments like "-g -D3D11"  and in the runtime_test.cpp 
`XrResult RuntimeTestXrEnumerateInstanceExtensionProperties(const char *layerName, uint32_t propertyCapacityInput,
                                                           uint32_t *propertyCountOutput, XrExtensionProperties *properties) {
    if (nullptr != layerName) {
        return XR_ERROR_API_LAYER_NOT_PRESENT;
    }
    *propertyCountOutput = 1;
    if (0 != propertyCapacityInput) {

        strcpy(properties[0].extensionName, "XR_KHR_D3D11_enable");
        properties[0].specVersion = 28;
    }
    return XR_SUCCESS;
}`
that all?
Can you tell me how to develop myself "Extensions "?
I do not know if you ever used SteamVR.If you know SteamVR can you tell me in OpenXR which part is the most  similar with "custom driver" in SteamVR?
Thank you for your patience and advise.

**Comment by rpavlik** [comment]
Ah, I see. OpenXR 1.0 does not include a device driver interface yet - it's under discussion for possible future addition. Right now, you need your own runtime or plugin into an existing runtime. So, that would mean working with Microsoft to get in their WinMR runtime, working with Collabora on the Monado open-source runtime, or with another vendor who has a runtime.

Extensions in OpenXR are like extensions in Vulkan or OpenGL - optional parts of the spec that a runtime/driver may or may not support.

**Comment by SlimSnow** [comment]
@rpavlik  All right ,Thank you for your patience and advise again.
