### ISSUE TITLE
One active runtime can support multiply session in the same time?

### ISSUE THREAD

**Issue by SlimSnow** [KhronosGroup/OpenXR-SDK-Source#93]
Actually,I wonder may I open multiply OpenXR app at the same time like the normal desktop app.

**Comment by rpavlik** [comment]
That depends on the runtime. It's not required by the spec, but in practice many runtimes will offer this.

You might want to try asking some of these questions in the forum https://community.khronos.org/c/openxr or Slack chat https://khr.io/slack/ to reach more people more quickly.

**Comment by SlimSnow** [comment]
@rpavlik Thank you very much,that is a very helpful advice.
