### ISSUE TITLE
Change exception handling to be on by default?

### ISSUE THREAD

**Issue by rpavlik** [KhronosGroup/OpenXR-SDK-Source#94]
@zheqiMicrosoft  looking for your input here.

I'm documenting and cleaning up some things, and I realized I think I made my optional exception handling too dangerous. There's a define `XRLOADER_ENABLE_EXCEPTION_HANDLING` that you must enable except in two conditions (excerpt from in-progress note in docs):

  * Due to a project policy, you're using a custom standard-library build
    that has exception throwing disabled.
    (The loader itself does not throw any exceptions but it uses standard
    library functionality that may throw.)
  * You're developing or debugging the loader and want exceptions to go
    uncaught to trigger a debugger.

However, if somebody doesn't use CMake, it's easy to forget to fail to define something, so it seems like the better, safer default is to catch exceptions unless `XRLOADER_DISABLE_EXCEPTION_HANDLING` is defined.

I imagine for your uses, you could probably add that define in to your alternate build system, but I wanted to find out for sure before I made a PR.

**Comment by RafaelCintron** [comment]
@rpavlik , this is fine with us.
